import { Prisma, type PartClass, type PrismaClient, type Rarity } from '@prisma/client';
import { defaultConnectorRules } from '../../src/parts/connector-rules.js';

// The factory catalog, written as FAMILIES: one entry per part family and size, with its five
// rarity tiers (COMMON → LEGENDARY) listed explicitly. A tier's `partType` is the family `base` plus
// its rarity suffix (`hull`, `hull_uncommon`, `hull_rare`, `hull_epic`, `hull_legendary`) — the
// naming the in-place upgrade follows to find the next tier — so every family, in every size,
// has all five tiers and the common tier carries the bare name. Sizes of one kind (small / medium /
// large engines, 1×1 / 2×2 / 4×4 reactors...) are separate families with their own stats: a bigger
// part gives more per cell for more mass, structure, power and price.
//
// Like every seeded value these only FILL what is missing: a row an admin edited keeps its values
// (DB wins over TS defaults), so a fresh database gets exactly this catalog.
type Localized = { en: string; 'pt-BR': string };

type SeedPart = {
  partType: string;
  displayName: Localized;
  description: Localized;
  partClass: PartClass;
  rarity: Rarity;
  w: number;
  h: number;
  mass: number;
  structureCost: number;
  basePrice: number;
  scrapValue: number;
  partHp: number;
  pot?: number;
  pdf?: number;
  bli?: number;
  esc?: number;
  sen?: number;
  crg?: number;
  min?: number;
  energyCont?: number;
  energyCombat?: number;
  fuelCap?: number;
  fuelUse?: number;
  batCharge?: number;
  batOutput?: number;
  batInput?: number;
  /** Flags read by mission requirements: `pressurized` (passenger space), `lifeSupport`. */
  specialProp?: {
    pressurized?: boolean;
    lifeSupport?: boolean;
    shieldRegen?: number;
    /** Power a context system (weapon, shield, mining rig) keeps drawing while idle (default 1). */
    idlePower?: number;
    /** Bridge: cells of loose parts the ship carries for free (the rest takes cargo space). */
    storageSlots?: number;
    /** A weapon whose hits ignore the armor's flat cut (the shield and the armor pool still count). */
    armorPiercing?: boolean;
  };
};

type Tier = Omit<SeedPart, 'partType' | 'displayName' | 'description' | 'partClass' | 'w' | 'h'> & {
  name?: Localized;
  description?: Localized;
};

type Family = {
  base: string;
  partClass: PartClass;
  w: number;
  h: number;
  name: Localized;
  description: Localized;
  tiers: Tier[];
};

const RARITY_SUFFIX: Record<string, string> = {
  COMMON: '',
  UNCOMMON: '_uncommon',
  RARE: '_rare',
  EPIC: '_epic',
  LEGENDARY: '_legendary',
};

function rowsOf(family: Family): SeedPart[] {
  return family.tiers.map(({ name, description, ...tier }) => ({
    ...tier,
    partType: `${family.base}${RARITY_SUFFIX[tier.rarity] ?? ''}`,
    displayName: name ?? family.name,
    description: description ?? family.description,
    partClass: family.partClass,
    w: family.w,
    h: family.h,
  }));
}

const FAMILIES: Family[] = [
  {
    base: 'bridge',
    partClass: 'BRIDGE',
    w: 1,
    h: 1,
    name: { en: 'Bridge', 'pt-BR': 'Ponte de Comando' },
    description: {
      en: 'The command core of your ship. Every ship needs exactly one. It keeps the pilot alive if the rest of the ship is lost, and it sets how much structure (total build weight) the ship can carry.',
      'pt-BR':
        'O núcleo de comando da sua nave. Toda nave precisa de exatamente uma. Ela mantém o piloto vivo se o resto da nave for perdido e define quanta estrutura (peso total de construção) a nave aguenta.',
    },
    tiers: [
      {
        rarity: 'COMMON',
        mass: 4,
        structureCost: -60,
        basePrice: 0,
        scrapValue: 0,
        partHp: 30,
        energyCont: -1,
        specialProp: { storageSlots: 4 },
      },
      {
        rarity: 'UNCOMMON',
        mass: 4,
        structureCost: -75,
        basePrice: 600,
        scrapValue: 150,
        partHp: 38,
        energyCont: -1,
        specialProp: { storageSlots: 6 },
        name: { en: 'Command Bridge II', 'pt-BR': 'Ponte de Comando II' },
        description: {
          en: 'An improved command core with a larger structure budget and tougher casing. Better avionics fit in the same compact frame.',
          'pt-BR':
            'Um núcleo de comando aprimorado com maior orçamento de estrutura e casco mais resistente. Aviônicos melhores cabem no mesmo quadro compacto.',
        },
      },
      {
        rarity: 'RARE',
        mass: 3,
        structureCost: -120,
        basePrice: 2400,
        scrapValue: 600,
        partHp: 55,
        energyCont: -1,
        specialProp: { storageSlots: 8 },
        name: { en: 'Command Bridge III', 'pt-BR': 'Ponte de Comando III' },
        description: {
          en: 'A hardened command core for ambitious ships. Offers a much larger structure budget without growing heavier or hungrier.',
          'pt-BR':
            'Um núcleo de comando endurecido para naves ambiciosas. Oferece orçamento de estrutura bem maior sem ficar mais pesado ou faminto.',
        },
      },
      {
        rarity: 'EPIC',
        mass: 3,
        structureCost: -170,
        basePrice: 6000,
        scrapValue: 1500,
        partHp: 75,
        energyCont: -1,
        specialProp: { storageSlots: 12 },
        name: { en: 'Command Bridge IV', 'pt-BR': 'Ponte de Comando IV' },
        description: {
          en: 'A capital-grade command core. The structure budget is doubled compared to a basic bridge, yet the frame stays compact.',
          'pt-BR':
            'Um núcleo de comando de classe capital. O orçamento de estrutura é o dobro de uma ponte básica, mas o quadro permanece compacto.',
        },
      },
      {
        rarity: 'LEGENDARY',
        mass: 2,
        structureCost: -260,
        basePrice: 14000,
        scrapValue: 3500,
        partHp: 100,
        energyCont: -1,
        specialProp: { storageSlots: 16 },
        name: { en: 'Apex Command Core', 'pt-BR': 'Núcleo de Comando Apex' },
        description: {
          en: 'A near-mythical command core. Its compact shell houses enough structure budget for a small fleet, and the pilot capsule can survive almost anything.',
          'pt-BR':
            'Um núcleo de comando quase mítico. Sua carcaça compacta abriga orçamento de estrutura suficiente para uma pequena frota, e a cápsula do piloto sobrevive a quase tudo.',
        },
      },
    ],
  },
  {
    base: 'engine_chem_large',
    partClass: 'ENGINE',
    w: 2,
    h: 2,
    name: { en: 'Large Chemical Engine', 'pt-BR': 'Motor Químico Grande' },
    description: {
      en: 'Big thrust for big ships. Moves heavy cargo or warship builds at a decent speed, but it is heavy, takes a 2×2 block and burns fuel fast. Needs a fuel tank.',
      'pt-BR':
        'Muito empuxo para naves grandes. Move construções pesadas de carga ou guerra numa velocidade decente, mas é pesado, ocupa um bloco 2×2 e queima combustível rápido. Precisa de um tanque de combustível.',
    },
    tiers: [
      {
        rarity: 'COMMON',
        mass: 16.3,
        structureCost: 22,
        basePrice: 400,
        scrapValue: 100,
        partHp: 36,
        pot: 112,
        energyCont: 5,
        fuelUse: 28,
      },
      {
        rarity: 'UNCOMMON',
        mass: 14,
        structureCost: 20,
        basePrice: 800,
        scrapValue: 200,
        partHp: 45,
        pot: 143,
        energyCont: 7,
        fuelUse: 32,
      },
      {
        rarity: 'RARE',
        mass: 12,
        structureCost: 18,
        basePrice: 1600,
        scrapValue: 400,
        partHp: 57,
        pot: 179,
        energyCont: 9,
        fuelUse: 40,
      },
      {
        rarity: 'EPIC',
        mass: 10,
        structureCost: 15,
        basePrice: 3200,
        scrapValue: 800,
        partHp: 69,
        pot: 224,
        energyCont: 11,
        fuelUse: 48,
      },
      {
        rarity: 'LEGENDARY',
        mass: 8,
        structureCost: 13,
        basePrice: 6400,
        scrapValue: 1600,
        partHp: 87,
        pot: 282,
        energyCont: 13,
        fuelUse: 60,
      },
    ],
  },
  {
    base: 'engine_chem_medium',
    partClass: 'ENGINE',
    w: 1,
    h: 2,
    name: { en: 'Medium Chemical Engine', 'pt-BR': 'Motor Químico Médio' },
    description: {
      en: 'The all-round engine: clearly more thrust than the small one, for more fuel use and mass. A good fit for ships that carry cargo or armor. Needs a fuel tank.',
      'pt-BR':
        'O motor versátil: bem mais empuxo que o pequeno, com mais consumo e massa. Serve bem para naves com carga ou blindagem. Precisa de um tanque de combustível.',
    },
    tiers: [
      {
        rarity: 'COMMON',
        mass: 6,
        structureCost: 10,
        basePrice: 300,
        scrapValue: 75,
        partHp: 30,
        pot: 52,
        energyCont: 4,
        fuelUse: 14,
      },
      {
        rarity: 'UNCOMMON',
        mass: 5,
        structureCost: 8,
        basePrice: 600,
        scrapValue: 150,
        partHp: 39,
        pot: 67,
        energyCont: 5,
        fuelUse: 16,
      },
      {
        rarity: 'RARE',
        mass: 4,
        structureCost: 8,
        basePrice: 1200,
        scrapValue: 300,
        partHp: 50,
        pot: 84,
        energyCont: 7,
        fuelUse: 20,
      },
      {
        rarity: 'EPIC',
        mass: 4,
        structureCost: 6,
        basePrice: 2400,
        scrapValue: 600,
        partHp: 60,
        pot: 105,
        energyCont: 8,
        fuelUse: 24,
      },
      {
        rarity: 'LEGENDARY',
        mass: 3,
        structureCost: 6,
        basePrice: 4800,
        scrapValue: 1200,
        partHp: 75,
        pot: 132,
        energyCont: 10,
        fuelUse: 30,
      },
    ],
  },
  {
    base: 'engine_chem_small',
    partClass: 'ENGINE',
    w: 1,
    h: 1,
    name: { en: 'Small Chemical Engine', 'pt-BR': 'Motor Químico Pequeno' },
    description: {
      en: 'A light rocket engine that moves the ship. It burns fuel, so you also need a fuel tank. Cheap and thrifty, but too weak to push a heavy ship fast.',
      'pt-BR':
        'Um motor a foguete leve que move a nave. Ele queima combustível, então você também precisa de um tanque. Barato e econômico, mas fraco demais para mover uma nave pesada rápido.',
    },
    tiers: [
      {
        rarity: 'COMMON',
        mass: 3,
        structureCost: 6,
        basePrice: 100,
        scrapValue: 25,
        partHp: 20,
        pot: 25,
        energyCont: 2,
        fuelUse: 7,
      },
      {
        rarity: 'UNCOMMON',
        mass: 3,
        structureCost: 5,
        basePrice: 200,
        scrapValue: 50,
        partHp: 26,
        pot: 32,
        energyCont: 3,
        fuelUse: 8,
        name: { en: 'Improved Chemical Engine', 'pt-BR': 'Motor Químico Aprimorado' },
        description: {
          en: 'A tuned chemical engine with more thrust and better fuel efficiency. Fits in the same 1×1 slot as the basic small engine.',
          'pt-BR':
            'Um motor químico sintonizado com mais empuxo e melhor eficiência de combustível. Cabe no mesmo slot 1×1 do motor pequeno básico.',
        },
      },
      {
        rarity: 'RARE',
        mass: 2,
        structureCost: 5,
        basePrice: 400,
        scrapValue: 100,
        partHp: 34,
        pot: 40,
        energyCont: 4,
        fuelUse: 10,
        name: {
          en: 'High-Performance Chemical Engine',
          'pt-BR': 'Motor Químico de Alto Desempenho',
        },
        description: {
          en: 'A compact high-thrust chemical engine. Lighter and more powerful than lower-tier small engines, with manageable fuel use.',
          'pt-BR':
            'Um motor químico compacto de alto empuxo. Mais leve e poderoso que motores pequenos de tiers inferiores, com consumo de combustível controlado.',
        },
      },
      {
        rarity: 'EPIC',
        mass: 2,
        structureCost: 4,
        basePrice: 800,
        scrapValue: 200,
        partHp: 40,
        pot: 50,
        energyCont: 5,
        fuelUse: 12,
        name: { en: 'Turbocharged Chemical Engine', 'pt-BR': 'Motor Químico Turbinado' },
        description: {
          en: 'A miniaturized engine with double the thrust of a basic small engine. Surprisingly light for its power output.',
          'pt-BR':
            'Um motor miniaturizado com o dobro do empuxo de um motor pequeno básico. Surpreendentemente leve para sua potência.',
        },
      },
      {
        rarity: 'LEGENDARY',
        mass: 1,
        structureCost: 4,
        basePrice: 1600,
        scrapValue: 400,
        partHp: 50,
        pot: 63,
        energyCont: 6,
        fuelUse: 15,
        name: { en: 'Fusion Torch Engine', 'pt-BR': 'Motor Tocha de Fusão' },
        description: {
          en: 'A legendary chemical drive. Its tiny frame outputs thrust that rivals full-size engines, with reasonable fuel consumption.',
          'pt-BR':
            'Uma propulsão química lendária. Seu minúsculo quadro entrega empuxo rivalizando motores de tamanho completo, com consumo de combustível razoável.',
        },
      },
    ],
  },
  {
    base: 'engine_ion_medium',
    partClass: 'ENGINE',
    w: 2,
    h: 2,
    name: { en: 'Heavy Ion Engine', 'pt-BR': 'Motor Iônico Pesado' },
    description: {
      en: 'A 2×2 ion engine: the strongest fuel-free thrust, and a big appetite for power.',
      'pt-BR':
        'Um motor iônico 2×2: o empuxo mais forte sem combustível, e um grande apetite por energia.',
    },
    tiers: [
      {
        rarity: 'COMMON',
        mass: 7.4,
        structureCost: 18,
        basePrice: 720,
        scrapValue: 180,
        partHp: 54,
        pot: 86,
        energyCont: -12,
      },
      {
        rarity: 'UNCOMMON',
        mass: 7.4,
        structureCost: 15,
        basePrice: 1450,
        scrapValue: 362,
        partHp: 72,
        pot: 115,
        energyCont: -16,
      },
      {
        rarity: 'RARE',
        mass: 3.7,
        structureCost: 15,
        basePrice: 2900,
        scrapValue: 725,
        partHp: 94,
        pot: 144,
        energyCont: -20,
      },
      {
        rarity: 'EPIC',
        mass: 3.7,
        structureCost: 11,
        basePrice: 5750,
        scrapValue: 1438,
        partHp: 108,
        pot: 173,
        energyCont: -24,
      },
      {
        rarity: 'LEGENDARY',
        mass: 3.7,
        structureCost: 11,
        basePrice: 11500,
        scrapValue: 2875,
        partHp: 137,
        pot: 216,
        energyCont: -32,
      },
    ],
  },
  {
    base: 'engine_ion_micro',
    partClass: 'ENGINE',
    w: 1,
    h: 1,
    name: { en: 'Micro Ion Engine', 'pt-BR': 'Motor Iônico Micro' },
    description: {
      en: 'A tiny electric drive that burns no fuel, so no tank is needed. Its thrust is low: good for light ships and long trips where refuelling is a hassle. Needs steady power from a reactor or solar panel.',
      'pt-BR':
        'Um pequeno motor elétrico que não queima combustível, então não precisa de tanque. O empuxo é baixo: bom para naves leves e viagens longas em que reabastecer é um problema. Precisa de energia constante de um reator ou painel solar.',
    },
    tiers: [
      {
        rarity: 'COMMON',
        mass: 2,
        structureCost: 5,
        basePrice: 150,
        scrapValue: 38,
        partHp: 15,
        pot: 18,
        energyCont: -3,
      },
      {
        rarity: 'UNCOMMON',
        mass: 2,
        structureCost: 4,
        basePrice: 300,
        scrapValue: 75,
        partHp: 20,
        pot: 24,
        energyCont: -4,
        name: { en: 'Small Ion Engine', 'pt-BR': 'Motor Iônico Pequeno' },
        description: {
          en: 'A refined ion drive with more thrust than the micro model. Still needs no fuel and no tank.',
          'pt-BR':
            'Uma propulsão iônica refinada com mais empuxo que o modelo micro. Ainda não precisa de combustível nem tanque.',
        },
      },
      {
        rarity: 'RARE',
        mass: 1,
        structureCost: 4,
        basePrice: 600,
        scrapValue: 150,
        partHp: 26,
        pot: 30,
        energyCont: -5,
        name: { en: 'Efficient Ion Engine', 'pt-BR': 'Motor Iônico Eficiente' },
        description: {
          en: 'A lightweight ion engine with noticeably more thrust. Perfect for long-range scouts that never want to refuel.',
          'pt-BR':
            'Um motor iônico leve com empuxo visivelmente maior. Perfeito para scouts de longo alcance que nunca querem reabastecer.',
        },
      },
      {
        rarity: 'EPIC',
        mass: 1,
        structureCost: 3,
        basePrice: 1200,
        scrapValue: 300,
        partHp: 30,
        pot: 36,
        energyCont: -6,
        name: { en: 'High-Thrust Ion Drive', 'pt-BR': 'Propulsão Iônica de Alto Empuxo' },
        description: {
          en: 'A compact ion drive that doubles the thrust of a micro ion engine. No fuel, no tank, just steady electric thrust.',
          'pt-BR':
            'Uma propulsão iônica compacta que dobra o empuxo de um motor iônico micro. Sem combustível, sem tanque, só empuxo elétrico constante.',
        },
      },
      {
        rarity: 'LEGENDARY',
        mass: 1,
        structureCost: 3,
        basePrice: 2400,
        scrapValue: 600,
        partHp: 38,
        pot: 45,
        energyCont: -8,
        name: { en: 'Aurora Drive', 'pt-BR': 'Propulsão Aurora' },
        description: {
          en: 'A legendary ion drive. Its acceleration rivals chemical engines while needing no fuel at all.',
          'pt-BR':
            'Uma propulsão iônica lendária. Sua aceleração rivaliza motores químicos sem precisar de combustível.',
        },
      },
    ],
  },
  {
    base: 'engine_ion_small',
    partClass: 'ENGINE',
    w: 1,
    h: 2,
    name: { en: 'Ion Engine', 'pt-BR': 'Motor Iônico' },
    description: {
      en: 'A larger ion engine (1×2): more thrust than the micro engine for more power, and still no fuel.',
      'pt-BR':
        'Um motor iônico maior (1×2): mais empuxo que o micro por mais energia, e ainda sem combustível.',
    },
    tiers: [
      {
        rarity: 'COMMON',
        mass: 3.7,
        structureCost: 9,
        basePrice: 330,
        scrapValue: 82,
        partHp: 27,
        pot: 40,
        energyCont: -6,
      },
      {
        rarity: 'UNCOMMON',
        mass: 3.7,
        structureCost: 7,
        basePrice: 660,
        scrapValue: 165,
        partHp: 36,
        pot: 53,
        energyCont: -8,
      },
      {
        rarity: 'RARE',
        mass: 1.8,
        structureCost: 7,
        basePrice: 1300,
        scrapValue: 325,
        partHp: 47,
        pot: 66,
        energyCont: -10,
      },
      {
        rarity: 'EPIC',
        mass: 1.8,
        structureCost: 6,
        basePrice: 2650,
        scrapValue: 662,
        partHp: 54,
        pot: 79,
        energyCont: -12,
      },
      {
        rarity: 'LEGENDARY',
        mass: 1.8,
        structureCost: 6,
        basePrice: 5300,
        scrapValue: 1325,
        partHp: 68,
        pot: 99,
        energyCont: -16,
      },
    ],
  },
  {
    base: 'tank_huge',
    partClass: 'TANK',
    w: 2,
    h: 2,
    name: { en: 'Huge Fuel Tank', 'pt-BR': 'Tanque de Combustível Enorme' },
    description: {
      en: 'A 2×2 fuel tank: the most fuel per cell, for ships that cross the whole map without stopping.',
      'pt-BR':
        'Um tanque de combustível 2×2: o máximo de combustível por célula, para naves que cruzam o mapa inteiro sem parar.',
    },
    tiers: [
      {
        rarity: 'COMMON',
        mass: 18.4,
        structureCost: 15,
        basePrice: 880,
        scrapValue: 220,
        partHp: 90,
        energyCont: -4,
        fuelCap: 1320,
      },
      {
        rarity: 'UNCOMMON',
        mass: 17.7,
        structureCost: 15,
        basePrice: 1400,
        scrapValue: 350,
        partHp: 108,
        energyCont: -4,
        fuelCap: 1650,
      },
      {
        rarity: 'RARE',
        mass: 16.9,
        structureCost: 15,
        basePrice: 2250,
        scrapValue: 562,
        partHp: 126,
        energyCont: -4,
        fuelCap: 1980,
      },
      {
        rarity: 'EPIC',
        mass: 16.2,
        structureCost: 15,
        basePrice: 3600,
        scrapValue: 900,
        partHp: 144,
        energyCont: -4,
        fuelCap: 2310,
      },
      {
        rarity: 'LEGENDARY',
        mass: 15.5,
        structureCost: 15,
        basePrice: 5750,
        scrapValue: 1438,
        partHp: 162,
        energyCont: -4,
        fuelCap: 2640,
      },
    ],
  },
  {
    base: 'tank_large',
    partClass: 'TANK',
    w: 3,
    h: 1,
    name: { en: 'Large Fuel Tank', 'pt-BR': 'Tanque de Combustível Grande' },
    description: {
      en: 'The big reserve for long hauls: three times the small tank in fuel. Takes three squares in a row.',
      'pt-BR':
        'A grande reserva para viagens longas: três vezes o combustível do tanque pequeno. Ocupa três quadrados em linha.',
    },
    tiers: [
      {
        rarity: 'COMMON',
        mass: 10,
        structureCost: 8,
        basePrice: 600,
        scrapValue: 150,
        partHp: 45,
        energyCont: -1,
        fuelCap: 900,
      },
      {
        rarity: 'UNCOMMON',
        mass: 9.6,
        structureCost: 8,
        basePrice: 960,
        scrapValue: 240,
        partHp: 54,
        energyCont: -1,
        fuelCap: 1125,
        description: {
          en: 'The big reserve for long hauls: three times the small tank in fuel. Takes three squares in a row. Reinforced casing and better sealing: a little more fuel, a little lighter.',
          'pt-BR':
            'A grande reserva para viagens longas: três vezes o combustível do tanque pequeno. Ocupa três quadrados em linha. Casco reforçado e melhor vedação: um pouco mais de combustível e mais leve.',
        },
      },
      {
        rarity: 'RARE',
        mass: 9.2,
        structureCost: 8,
        basePrice: 1550,
        scrapValue: 388,
        partHp: 63,
        energyCont: -1,
        fuelCap: 1350,
        description: {
          en: 'The big reserve for long hauls: three times the small tank in fuel. Takes three squares in a row. Advanced alloys make it lighter and tougher while holding more.',
          'pt-BR':
            'A grande reserva para viagens longas: três vezes o combustível do tanque pequeno. Ocupa três quadrados em linha. Ligas avançadas o deixam mais leve e resistente guardando mais.',
        },
      },
      {
        rarity: 'EPIC',
        mass: 8.8,
        structureCost: 8,
        basePrice: 2450,
        scrapValue: 612,
        partHp: 72,
        energyCont: -1,
        fuelCap: 1575,
        description: {
          en: 'The big reserve for long hauls: three times the small tank in fuel. Takes three squares in a row. Expedition grade: more fuel for less weight.',
          'pt-BR':
            'A grande reserva para viagens longas: três vezes o combustível do tanque pequeno. Ocupa três quadrados em linha. Padrão de expedição: mais combustível por menos peso.',
        },
      },
      {
        rarity: 'LEGENDARY',
        mass: 8.4,
        structureCost: 8,
        basePrice: 3950,
        scrapValue: 988,
        partHp: 81,
        energyCont: -1,
        fuelCap: 1800,
        description: {
          en: 'The big reserve for long hauls: three times the small tank in fuel. Takes three squares in a row. Compressed-core build: the best tank of its size.',
          'pt-BR':
            'A grande reserva para viagens longas: três vezes o combustível do tanque pequeno. Ocupa três quadrados em linha. Construção de núcleo comprimido: o melhor tanque do seu tamanho.',
        },
      },
    ],
  },
  {
    base: 'tank_medium',
    partClass: 'TANK',
    w: 2,
    h: 1,
    name: { en: 'Medium Fuel Tank', 'pt-BR': 'Tanque de Combustível Médio' },
    description: {
      en: 'A tank twice the size of the small one: twice the fuel for a bit more mass. Takes two squares in a row.',
      'pt-BR':
        'Um tanque com o dobro do tamanho do pequeno: o dobro de combustível por um pouco mais de massa. Ocupa dois quadrados em linha.',
    },
    tiers: [
      {
        rarity: 'COMMON',
        mass: 8,
        structureCost: 6,
        basePrice: 400,
        scrapValue: 100,
        partHp: 35,
        energyCont: -1,
        fuelCap: 600,
      },
      {
        rarity: 'UNCOMMON',
        mass: 7.7,
        structureCost: 6,
        basePrice: 640,
        scrapValue: 160,
        partHp: 42,
        energyCont: -1,
        fuelCap: 750,
        description: {
          en: 'A tank twice the size of the small one: twice the fuel for a bit more mass. Takes two squares in a row. Reinforced casing and better sealing: a little more fuel, a little lighter.',
          'pt-BR':
            'Um tanque com o dobro do tamanho do pequeno: o dobro de combustível por um pouco mais de massa. Ocupa dois quadrados em linha. Casco reforçado e melhor vedação: um pouco mais de combustível e mais leve.',
        },
      },
      {
        rarity: 'RARE',
        mass: 7.4,
        structureCost: 6,
        basePrice: 1000,
        scrapValue: 250,
        partHp: 49,
        energyCont: -1,
        fuelCap: 900,
        description: {
          en: 'A tank twice the size of the small one: twice the fuel for a bit more mass. Takes two squares in a row. Advanced alloys make it lighter and tougher while holding more.',
          'pt-BR':
            'Um tanque com o dobro do tamanho do pequeno: o dobro de combustível por um pouco mais de massa. Ocupa dois quadrados em linha. Ligas avançadas o deixam mais leve e resistente guardando mais.',
        },
      },
      {
        rarity: 'EPIC',
        mass: 7,
        structureCost: 6,
        basePrice: 1650,
        scrapValue: 412,
        partHp: 56,
        energyCont: -1,
        fuelCap: 1050,
        description: {
          en: 'A tank twice the size of the small one: twice the fuel for a bit more mass. Takes two squares in a row. Expedition grade: more fuel for less weight.',
          'pt-BR':
            'Um tanque com o dobro do tamanho do pequeno: o dobro de combustível por um pouco mais de massa. Ocupa dois quadrados em linha. Padrão de expedição: mais combustível por menos peso.',
        },
      },
      {
        rarity: 'LEGENDARY',
        mass: 6.7,
        structureCost: 6,
        basePrice: 2600,
        scrapValue: 650,
        partHp: 63,
        energyCont: -1,
        fuelCap: 1200,
        description: {
          en: 'A tank twice the size of the small one: twice the fuel for a bit more mass. Takes two squares in a row. Compressed-core build: the best tank of its size.',
          'pt-BR':
            'Um tanque com o dobro do tamanho do pequeno: o dobro de combustível por um pouco mais de massa. Ocupa dois quadrados em linha. Construção de núcleo comprimido: o melhor tanque do seu tamanho.',
        },
      },
    ],
  },
  {
    base: 'tank_small',
    partClass: 'TANK',
    w: 1,
    h: 1,
    name: { en: 'Small Fuel Tank', 'pt-BR': 'Tanque de Combustível Pequeno' },
    description: {
      en: 'Holds your fuel. Every chemical engine burns fuel, so a ship with one needs at least one tank; more tanks mean more range between refuels. Adds mass and uses structure.',
      'pt-BR':
        'Guarda o seu combustível. Todo motor químico queima combustível, então uma nave com um precisa de pelo menos um tanque; mais tanques significam mais alcance entre reabastecimentos. Adiciona massa e usa estrutura.',
    },
    tiers: [
      {
        rarity: 'COMMON',
        mass: 5,
        structureCost: 4,
        basePrice: 200,
        scrapValue: 50,
        partHp: 25,
        energyCont: -1,
        fuelCap: 300,
      },
      {
        rarity: 'UNCOMMON',
        mass: 4.8,
        structureCost: 4,
        basePrice: 320,
        scrapValue: 80,
        partHp: 30,
        energyCont: -1,
        fuelCap: 375,
        description: {
          en: 'Holds your fuel. Every chemical engine burns fuel, so a ship with one needs at least one tank; more tanks mean more range between refuels. Adds mass and uses structure. Reinforced casing and better sealing: a little more fuel, a little lighter.',
          'pt-BR':
            'Guarda o seu combustível. Todo motor químico queima combustível, então uma nave com um precisa de pelo menos um tanque; mais tanques significam mais alcance entre reabastecimentos. Adiciona massa e usa estrutura. Casco reforçado e melhor vedação: um pouco mais de combustível e mais leve.',
        },
      },
      {
        rarity: 'RARE',
        mass: 4.6,
        structureCost: 4,
        basePrice: 510,
        scrapValue: 128,
        partHp: 35,
        energyCont: -1,
        fuelCap: 450,
        description: {
          en: 'Holds your fuel. Every chemical engine burns fuel, so a ship with one needs at least one tank; more tanks mean more range between refuels. Adds mass and uses structure. Advanced alloys make it lighter and tougher while holding more.',
          'pt-BR':
            'Guarda o seu combustível. Todo motor químico queima combustível, então uma nave com um precisa de pelo menos um tanque; mais tanques significam mais alcance entre reabastecimentos. Adiciona massa e usa estrutura. Ligas avançadas o deixam mais leve e resistente guardando mais.',
        },
      },
      {
        rarity: 'EPIC',
        mass: 4.4,
        structureCost: 4,
        basePrice: 820,
        scrapValue: 205,
        partHp: 40,
        energyCont: -1,
        fuelCap: 525,
        description: {
          en: 'Holds your fuel. Every chemical engine burns fuel, so a ship with one needs at least one tank; more tanks mean more range between refuels. Adds mass and uses structure. Expedition grade: more fuel for less weight.',
          'pt-BR':
            'Guarda o seu combustível. Todo motor químico queima combustível, então uma nave com um precisa de pelo menos um tanque; mais tanques significam mais alcance entre reabastecimentos. Adiciona massa e usa estrutura. Padrão de expedição: mais combustível por menos peso.',
        },
      },
      {
        rarity: 'LEGENDARY',
        mass: 4.2,
        structureCost: 4,
        basePrice: 1300,
        scrapValue: 325,
        partHp: 45,
        energyCont: -1,
        fuelCap: 600,
        description: {
          en: 'Holds your fuel. Every chemical engine burns fuel, so a ship with one needs at least one tank; more tanks mean more range between refuels. Adds mass and uses structure. Compressed-core build: the best tank of its size.',
          'pt-BR':
            'Guarda o seu combustível. Todo motor químico queima combustível, então uma nave com um precisa de pelo menos um tanque; mais tanques significam mais alcance entre reabastecimentos. Adiciona massa e usa estrutura. Construção de núcleo comprimido: o melhor tanque do seu tamanho.',
        },
      },
    ],
  },
  {
    base: 'battery_bank',
    partClass: 'BATTERY',
    w: 2,
    h: 2,
    name: { en: 'Battery Bank', 'pt-BR': 'Banco de Baterias' },
    description: {
      en: 'A 2×2 battery bank: a deep reserve for heavy weapons and shields.',
      'pt-BR': 'Um banco de baterias 2×2: uma reserva profunda para armas e escudos pesados.',
    },
    tiers: [
      {
        rarity: 'COMMON',
        mass: 30.1,
        structureCost: 30,
        basePrice: 530,
        scrapValue: 132,
        partHp: 50,
        batCharge: 1620,
        batOutput: 368,
        batInput: 184,
      },
      {
        rarity: 'UNCOMMON',
        mass: 25.8,
        structureCost: 26,
        basePrice: 920,
        scrapValue: 230,
        partHp: 63,
        batCharge: 2070,
        batOutput: 460,
        batInput: 230,
      },
      {
        rarity: 'RARE',
        mass: 22.1,
        structureCost: 22,
        basePrice: 1600,
        scrapValue: 400,
        partHp: 79,
        batCharge: 2645,
        batOutput: 575,
        batInput: 288,
      },
      {
        rarity: 'EPIC',
        mass: 18.4,
        structureCost: 18,
        basePrice: 2750,
        scrapValue: 688,
        partHp: 101,
        batCharge: 3335,
        batOutput: 736,
        batInput: 368,
      },
      {
        rarity: 'LEGENDARY',
        mass: 14.7,
        structureCost: 15,
        basePrice: 4600,
        scrapValue: 1150,
        partHp: 126,
        batCharge: 4140,
        batOutput: 920,
        batInput: 460,
      },
    ],
  },
  {
    base: 'battery_large',
    partClass: 'BATTERY',
    w: 1,
    h: 2,
    name: { en: 'Large Battery', 'pt-BR': 'Bateria Grande' },
    description: {
      en: 'A large energy store for power-hungry builds (lasers plus a shield). Far more charge and output than the small battery, but heavy and a 1×2 block.',
      'pt-BR':
        'Um grande estoque de energia para construções famintas por energia (lasers mais escudo). Muito mais carga e saída que a bateria pequena, mas pesada e ocupa um bloco 1×2.',
    },
    tiers: [
      {
        rarity: 'COMMON',
        mass: 16.3,
        structureCost: 16,
        basePrice: 230,
        scrapValue: 58,
        partHp: 28,
        batCharge: 704,
        batOutput: 160,
        batInput: 80,
      },
      {
        rarity: 'UNCOMMON',
        mass: 14,
        structureCost: 14,
        basePrice: 400,
        scrapValue: 100,
        partHp: 35,
        batCharge: 900,
        batOutput: 200,
        batInput: 100,
      },
      {
        rarity: 'RARE',
        mass: 12,
        structureCost: 12,
        basePrice: 700,
        scrapValue: 175,
        partHp: 44,
        batCharge: 1150,
        batOutput: 250,
        batInput: 125,
        name: { en: 'Heavy Battery Bank', 'pt-BR': 'Banco de Baterias Pesado' },
        description: {
          en: 'A reinforced large battery with denser cells. Holds more charge and recharges faster while shaving off mass and structure cost.',
          'pt-BR':
            'Uma bateria grande reforçada com células mais densas. Guarda mais carga e recarrega mais rápido enquanto reduz massa e custo de estrutura.',
        },
      },
      {
        rarity: 'EPIC',
        mass: 10,
        structureCost: 10,
        basePrice: 1200,
        scrapValue: 300,
        partHp: 56,
        batCharge: 1450,
        batOutput: 320,
        batInput: 160,
        name: { en: 'Industrial Capacitor Bank', 'pt-BR': 'Banco de Capacitores Industrial' },
        description: {
          en: 'A high-end large battery for capital-grade energy weapons and shields. Doubles the charge of a basic large battery with a lighter frame.',
          'pt-BR':
            'Uma bateria grande de alta qualidade para armas de energia e escudos de classe capital. Dobra a carga de uma bateria grande básica com um quadro mais leve.',
        },
      },
      {
        rarity: 'LEGENDARY',
        mass: 8,
        structureCost: 8,
        basePrice: 2000,
        scrapValue: 500,
        partHp: 70,
        batCharge: 1800,
        batOutput: 400,
        batInput: 200,
        name: { en: 'Abyssal Core Battery', 'pt-BR': 'Bateria de Núcleo Abissal' },
        description: {
          en: 'A legendary energy reservoir. Its 1×2 frame holds enough charge to power a warship, yet it weighs and costs structure like a mid-tier part.',
          'pt-BR':
            'Um reservatório de energia lendário. Seu quadro 1×2 guarda carga suficiente para alimentar uma nave de guerra, mas pesa e custa estrutura como uma peça de tier médio.',
        },
      },
    ],
  },
  {
    base: 'battery_small',
    partClass: 'BATTERY',
    w: 1,
    h: 1,
    name: { en: 'Small Battery', 'pt-BR': 'Bateria Pequena' },
    description: {
      en: 'Stores energy for combat. Shields and lasers draw from it during a fight, and if it cannot cover their demand the ship is not allowed to fly. Small and cheap.',
      'pt-BR':
        'Guarda energia para o combate. Escudos e lasers consomem dela durante a luta, e se ela não cobre a demanda a nave não pode voar. Pequena e barata.',
    },
    tiers: [
      {
        rarity: 'COMMON',
        mass: 5,
        structureCost: 6,
        basePrice: 150,
        scrapValue: 38,
        partHp: 20,
        batCharge: 300,
        batOutput: 80,
        batInput: 40,
      },
      {
        rarity: 'UNCOMMON',
        mass: 4,
        structureCost: 5,
        basePrice: 250,
        scrapValue: 63,
        partHp: 28,
        batCharge: 400,
        batOutput: 100,
        batInput: 50,
        name: { en: 'Medium Battery', 'pt-BR': 'Bateria Média' },
        description: {
          en: 'A more efficient combat energy store. Fits in the same 1×1 slot as a small battery but holds more charge and output while costing less structure.',
          'pt-BR':
            'Um armazenamento de energia de combate mais eficiente. Cabe no mesmo espaço 1×1 de uma bateria pequena, mas guarda mais carga e saída custando menos estrutura.',
        },
      },
      {
        rarity: 'RARE',
        mass: 3,
        structureCost: 4,
        basePrice: 400,
        scrapValue: 100,
        partHp: 36,
        batCharge: 500,
        batOutput: 130,
        batInput: 65,
        name: { en: 'High-Density Battery', 'pt-BR': 'Bateria de Alta Densidade' },
        description: {
          en: 'Advanced cell packing doubles the charge density of a basic small battery. Lighter and cheaper on structure than lower-tier models.',
          'pt-BR':
            'Empacotamento avançado de células dobra a densidade de carga de uma bateria pequena básica. Mais leve e mais barata em estrutura que modelos de tiers inferiores.',
        },
      },
      {
        rarity: 'EPIC',
        mass: 2,
        structureCost: 3,
        basePrice: 700,
        scrapValue: 175,
        partHp: 44,
        batCharge: 600,
        batOutput: 160,
        batInput: 80,
        name: { en: 'Compact Capacitor Bank', 'pt-BR': 'Banco de Capacitores Compacto' },
        description: {
          en: 'A tiny capacitor bank that holds twice the charge of a basic small battery. Fits in a featherweight frame and costs little structure.',
          'pt-BR':
            'Um minúsculo banco de capacitores que guarda o dobro da carga de uma bateria pequena básica. Cabe num quadro ultraleve e custa pouca estrutura.',
        },
      },
      {
        rarity: 'LEGENDARY',
        mass: 2,
        structureCost: 2,
        basePrice: 1200,
        scrapValue: 300,
        partHp: 52,
        batCharge: 750,
        batOutput: 200,
        batInput: 100,
        name: { en: 'Fusion Cell', 'pt-BR': 'Célula de Fusão' },
        description: {
          en: 'A near-mythical power cell. Its 1×1 shell outperforms most large batteries and costs almost nothing in structure or mass.',
          'pt-BR':
            'Uma célula de energia quase mítica. Sua carcaça 1×1 supera a maioria das baterias grandes e custa quase nada em estrutura ou massa.',
        },
      },
    ],
  },
  {
    base: 'reactor_nuclear',
    partClass: 'REACTOR',
    w: 2,
    h: 2,
    name: { en: 'Nuclear Reactor', 'pt-BR': 'Reator Nuclear' },
    description: {
      en: 'A heavy fission reactor with a very large power output, for builds full of power-hungry parts. Expensive and heavy (2×2).',
      'pt-BR':
        'Um reator de fissão pesado com produção de energia muito alta, para construções cheias de peças que consomem muita energia. Caro e pesado (2×2).',
    },
    tiers: [
      {
        rarity: 'COMMON',
        mass: 19.1,
        structureCost: 23,
        basePrice: 500,
        scrapValue: 125,
        partHp: 28,
        energyCont: 123,
      },
      {
        rarity: 'UNCOMMON',
        mass: 16.3,
        structureCost: 20,
        basePrice: 1000,
        scrapValue: 250,
        partHp: 33,
        energyCont: 149,
      },
      {
        rarity: 'RARE',
        mass: 14,
        structureCost: 18,
        basePrice: 2000,
        scrapValue: 500,
        partHp: 40,
        energyCont: 180,
      },
      {
        rarity: 'EPIC',
        mass: 12,
        structureCost: 16,
        basePrice: 4000,
        scrapValue: 1000,
        partHp: 48,
        energyCont: 218,
      },
      {
        rarity: 'LEGENDARY',
        mass: 9,
        structureCost: 13,
        basePrice: 8000,
        scrapValue: 2000,
        partHp: 61,
        energyCont: 273,
      },
    ],
  },
  {
    base: 'reactor_nuclear_large',
    partClass: 'REACTOR',
    w: 4,
    h: 4,
    name: { en: 'Nuclear Reactor Core', 'pt-BR': 'Núcleo de Reator Nuclear' },
    description: {
      en: 'A 4×4 reactor core. Enormous output for the cells it takes, with the mass and price of a small station.',
      'pt-BR':
        'Um núcleo de reator 4×4. Produção enorme pelas células que ocupa, com a massa e o preço de uma pequena estação.',
    },
    tiers: [
      {
        rarity: 'COMMON',
        mass: 70.1,
        structureCost: 84,
        basePrice: 2400,
        scrapValue: 600,
        partHp: 100,
        energyCont: 589,
      },
      {
        rarity: 'UNCOMMON',
        mass: 60.1,
        structureCost: 75,
        basePrice: 4800,
        scrapValue: 1200,
        partHp: 120,
        energyCont: 713,
      },
      {
        rarity: 'RARE',
        mass: 51.5,
        structureCost: 66,
        basePrice: 9600,
        scrapValue: 2400,
        partHp: 144,
        energyCont: 864,
      },
      {
        rarity: 'EPIC',
        mass: 44.2,
        structureCost: 59,
        basePrice: 19200,
        scrapValue: 4800,
        partHp: 173,
        energyCont: 1046,
      },
      {
        rarity: 'LEGENDARY',
        mass: 33.1,
        structureCost: 48,
        basePrice: 38400,
        scrapValue: 9600,
        partHp: 220,
        energyCont: 1310,
      },
    ],
  },
  {
    base: 'reactor_nuclear_small',
    partClass: 'REACTOR',
    w: 1,
    h: 1,
    name: { en: 'Compact Nuclear Reactor', 'pt-BR': 'Reator Nuclear Compacto' },
    description: {
      en: 'A shrunk-down nuclear reactor: far more power than a solar panel from a single cell, but less efficient than the full-size core.',
      'pt-BR':
        'Um reator nuclear reduzido: muito mais energia que um painel solar em uma única célula, mas menos eficiente que o núcleo de tamanho completo.',
    },
    tiers: [
      {
        rarity: 'COMMON',
        mass: 5.2,
        structureCost: 6,
        basePrice: 110,
        scrapValue: 28,
        partHp: 7,
        energyCont: 26,
      },
      {
        rarity: 'UNCOMMON',
        mass: 4.5,
        structureCost: 6,
        basePrice: 210,
        scrapValue: 52,
        partHp: 9,
        energyCont: 32,
      },
      {
        rarity: 'RARE',
        mass: 3.9,
        structureCost: 5,
        basePrice: 420,
        scrapValue: 105,
        partHp: 10,
        energyCont: 38,
      },
      {
        rarity: 'EPIC',
        mass: 3.3,
        structureCost: 4,
        basePrice: 850,
        scrapValue: 212,
        partHp: 13,
        energyCont: 46,
      },
      {
        rarity: 'LEGENDARY',
        mass: 2.5,
        structureCost: 4,
        basePrice: 1700,
        scrapValue: 425,
        partHp: 16,
        energyCont: 58,
      },
    ],
  },
  {
    base: 'reactor_solar',
    partClass: 'REACTOR',
    w: 1,
    h: 1,
    name: { en: 'Solar Panel', 'pt-BR': 'Painel Solar' },
    description: {
      en: 'A light solar array with a small but constant power output. Covers what engines, radar and rigs draw in flight at almost no weight.',
      'pt-BR':
        'Um painel solar leve com produção de energia pequena, mas constante. Cobre o que motores, radar e mineradoras consomem em voo, com quase nenhum peso.',
    },
    tiers: [
      {
        rarity: 'COMMON',
        mass: 2,
        structureCost: 3,
        basePrice: 300,
        scrapValue: 75,
        partHp: 15,
        energyCont: 3,
      },
      {
        rarity: 'UNCOMMON',
        mass: 2,
        structureCost: 3,
        basePrice: 600,
        scrapValue: 150,
        partHp: 20,
        energyCont: 4,
        name: { en: 'Advanced Solar Panel', 'pt-BR': 'Painel Solar Avançado' },
        description: {
          en: 'A more efficient solar array that generates more power from the same 1×1 footprint.',
          'pt-BR': 'Uma matriz solar mais eficiente que gera mais energia do mesmo espaço 1×1.',
        },
      },
      {
        rarity: 'RARE',
        mass: 1,
        structureCost: 2,
        basePrice: 1200,
        scrapValue: 300,
        partHp: 26,
        energyCont: 5,
        name: { en: 'High-Gain Solar Array', 'pt-BR': 'Matriz Solar de Alto Ganho' },
        description: {
          en: 'A focused solar collector with much higher output. Lighter on structure than lower-tier panels.',
          'pt-BR':
            'Um coletor solar focado com saída muito maior. Mais leve em estrutura que painéis de tiers inferiores.',
        },
      },
      {
        rarity: 'EPIC',
        mass: 1,
        structureCost: 2,
        basePrice: 2400,
        scrapValue: 600,
        partHp: 30,
        energyCont: 6,
        name: { en: 'Concentrator Solar Array', 'pt-BR': 'Matriz Solar Concentradora' },
        description: {
          en: 'A compact concentrator that doubles the output of a basic solar panel. Surprising power from a tiny frame.',
          'pt-BR':
            'Um concentrador compacto que dobra a saída de um painel solar básico. Energia surpreendente de um minúsculo quadro.',
        },
      },
      {
        rarity: 'LEGENDARY',
        mass: 1,
        structureCost: 1,
        basePrice: 4800,
        scrapValue: 1200,
        partHp: 38,
        energyCont: 8,
        name: { en: 'Star Heart Array', 'pt-BR': 'Matriz Coração Estelar' },
        description: {
          en: 'A legendary solar core. It squeezes almost as much power as a small reactor from a single solar panel.',
          'pt-BR':
            'Um núcleo solar lendário. Espreme quase tanto poder quanto um pequeno reator de um único painel solar.',
        },
      },
    ],
  },
  {
    base: 'reactor_solar_large',
    partClass: 'REACTOR',
    w: 2,
    h: 2,
    name: { en: 'Solar Wing', 'pt-BR': 'Asa Solar' },
    description: {
      en: 'A 2×2 solar wing: steady, clean power and more of it per cell than a single panel.',
      'pt-BR':
        'Uma asa solar 2×2: energia limpa e constante, e mais por célula que um painel isolado.',
    },
    tiers: [
      {
        rarity: 'COMMON',
        mass: 7.4,
        structureCost: 11,
        basePrice: 1300,
        scrapValue: 325,
        partHp: 54,
        energyCont: 13,
      },
      {
        rarity: 'UNCOMMON',
        mass: 7.4,
        structureCost: 11,
        basePrice: 2650,
        scrapValue: 662,
        partHp: 72,
        energyCont: 18,
      },
      {
        rarity: 'RARE',
        mass: 3.7,
        structureCost: 7,
        basePrice: 5300,
        scrapValue: 1325,
        partHp: 94,
        energyCont: 22,
      },
      {
        rarity: 'EPIC',
        mass: 3.7,
        structureCost: 7,
        basePrice: 10550,
        scrapValue: 2638,
        partHp: 108,
        energyCont: 26,
      },
      {
        rarity: 'LEGENDARY',
        mass: 3.7,
        structureCost: 4,
        basePrice: 21100,
        scrapValue: 5275,
        partHp: 137,
        energyCont: 35,
      },
    ],
  },
  {
    base: 'weapon_ballistic',
    partClass: 'WEAPON',
    w: 1,
    h: 1,
    name: { en: 'Cannon', 'pt-BR': 'Canhão' },
    description: {
      en: 'A basic cannon. Cheap, reliable damage that needs no energy: a good first weapon for escort missions. Modest firepower.',
      'pt-BR':
        'Um canhão básico. Dano barato e confiável que não usa energia: uma boa primeira arma para missões de escolta. Poder de fogo modesto.',
    },
    tiers: [
      {
        rarity: 'COMMON',
        mass: 3,
        structureCost: 5,
        basePrice: 120,
        scrapValue: 30,
        partHp: 20,
        pdf: 3,
        energyCont: -1,
      },
      {
        rarity: 'UNCOMMON',
        mass: 3,
        structureCost: 4,
        basePrice: 240,
        scrapValue: 60,
        partHp: 26,
        pdf: 4,
        energyCont: -1,
        name: { en: 'Heavy Cannon', 'pt-BR': 'Canhão Pesado' },
        description: {
          en: 'A reinforced cannon with heavier shells. Deals more damage than a basic cannon without needing energy.',
          'pt-BR':
            'Um canhão reforçado com projéteis mais pesados. Causa mais dano que um canhão básico sem precisar de energia.',
        },
      },
      {
        rarity: 'RARE',
        mass: 2,
        structureCost: 4,
        basePrice: 480,
        scrapValue: 120,
        partHp: 34,
        pdf: 5,
        energyCont: -1,
        name: { en: 'Auto-Cannon', 'pt-BR': 'Canhão Automático' },
        description: {
          en: 'A rapid-fire ballistic weapon. Lighter and more compact than lower-tier cannons while packing a bigger punch.',
          'pt-BR':
            'Uma arma balística de disparo rápido. Mais leve e compacta que canhões de tiers inferiores com um impacto maior.',
        },
      },
      {
        rarity: 'EPIC',
        mass: 2,
        structureCost: 3,
        basePrice: 960,
        scrapValue: 240,
        partHp: 40,
        pdf: 6,
        energyCont: -1,
        name: { en: 'Rail-Assisted Cannon', 'pt-BR': 'Canhão de Trilho' },
        description: {
          en: 'A high-velocity cannon with magnetic acceleration. Doubles the firepower of a basic cannon in the same 1×1 slot.',
          'pt-BR':
            'Um canhão de alta velocidade com aceleração magnética. Dobra o poder de fogo de um canhão básico no mesmo slot 1×1.',
        },
      },
      {
        rarity: 'LEGENDARY',
        mass: 1,
        structureCost: 3,
        basePrice: 1920,
        scrapValue: 480,
        partHp: 50,
        pdf: 8,
        energyCont: -1,
        name: { en: 'Doomsday Cannon', 'pt-BR': 'Canhão do Juízo Final' },
        description: {
          en: 'A legendary ballistic weapon. Its shells tear through hulls with terrifying force, yet the mount is surprisingly light.',
          'pt-BR':
            'Uma arma balística lendária. Seus projéteis rasgam cascos com força aterrorizante, mas a montagem é surpreendentemente leve.',
        },
      },
    ],
  },
  {
    base: 'weapon_ballistic_heavy',
    partClass: 'WEAPON',
    w: 1,
    h: 2,
    name: { en: 'Siege Cannon', 'pt-BR': 'Canhão de Cerco' },
    description: {
      en: 'A 1×2 cannon: more firepower than the standard cannon, and heavier.',
      'pt-BR': 'Um canhão 1×2: mais poder de fogo que o canhão padrão, e mais pesado.',
    },
    tiers: [
      {
        rarity: 'COMMON',
        mass: 5.5,
        structureCost: 9,
        basePrice: 220,
        scrapValue: 55,
        partHp: 36,
        pdf: 5,
        energyCont: -2,
      },
      {
        rarity: 'UNCOMMON',
        mass: 5.5,
        structureCost: 7,
        basePrice: 430,
        scrapValue: 108,
        partHp: 47,
        pdf: 7,
        energyCont: -2,
      },
      {
        rarity: 'RARE',
        mass: 3.7,
        structureCost: 7,
        basePrice: 860,
        scrapValue: 215,
        partHp: 61,
        pdf: 9,
        energyCont: -2,
      },
      {
        rarity: 'EPIC',
        mass: 3.7,
        structureCost: 6,
        basePrice: 1750,
        scrapValue: 438,
        partHp: 72,
        pdf: 11,
        energyCont: -2,
      },
      {
        rarity: 'LEGENDARY',
        mass: 1.8,
        structureCost: 6,
        basePrice: 3450,
        scrapValue: 862,
        partHp: 90,
        pdf: 14,
        energyCont: -2,
      },
    ],
  },
  {
    base: 'weapon_laser',
    partClass: 'WEAPON',
    w: 1,
    h: 1,
    name: { en: 'Laser', 'pt-BR': 'Laser' },
    description: {
      en: 'A precise energy weapon with more firepower than the cannon. It draws combat energy from your batteries every round, so pair it with a battery. Its beam cuts through armor.',
      'pt-BR':
        'Uma arma de energia precisa, com mais poder de fogo que o canhão. Consome energia de combate das baterias a cada rodada, então use com uma bateria. Seu feixe atravessa a armadura.',
    },
    tiers: [
      {
        rarity: 'COMMON',
        mass: 4.3,
        structureCost: 8,
        basePrice: 180,
        scrapValue: 45,
        partHp: 17,
        pdf: 3,
        energyCont: -2,
        energyCombat: -5,
        specialProp: { idlePower: 2, armorPiercing: true },
      },
      {
        rarity: 'UNCOMMON',
        mass: 3,
        structureCost: 7,
        basePrice: 350,
        scrapValue: 88,
        partHp: 22,
        pdf: 4,
        energyCont: -2,
        energyCombat: -5,
        specialProp: { idlePower: 2, armorPiercing: true },
      },
      {
        rarity: 'RARE',
        mass: 2,
        structureCost: 6,
        basePrice: 700,
        scrapValue: 175,
        partHp: 28,
        pdf: 5,
        energyCont: -2,
        energyCombat: -5,
        specialProp: { idlePower: 2, armorPiercing: true },
      },
      {
        rarity: 'EPIC',
        mass: 2,
        structureCost: 5,
        basePrice: 1400,
        scrapValue: 350,
        partHp: 34,
        pdf: 6,
        energyCont: -2,
        energyCombat: -5,
        specialProp: { idlePower: 2, armorPiercing: true },
      },
      {
        rarity: 'LEGENDARY',
        mass: 1,
        structureCost: 5,
        basePrice: 2800,
        scrapValue: 700,
        partHp: 42,
        pdf: 8,
        energyCont: -2,
        energyCombat: -5,
        specialProp: { idlePower: 2, armorPiercing: true },
      },
    ],
  },
  {
    base: 'weapon_laser_heavy',
    partClass: 'WEAPON',
    w: 1,
    h: 2,
    name: { en: 'Heavy Laser', 'pt-BR': 'Laser Pesado' },
    description: {
      en: 'A 1×2 laser: more firepower than the standard laser; its beam cuts through armor.',
      'pt-BR':
        'Um laser 1×2: mais poder de fogo que o laser padrão; seu feixe atravessa a armadura.',
    },
    tiers: [
      {
        rarity: 'COMMON',
        mass: 8,
        structureCost: 15,
        basePrice: 320,
        scrapValue: 80,
        partHp: 31,
        pdf: 6,
        energyCont: -4,
        energyCombat: -10,
        specialProp: { idlePower: 4, armorPiercing: true },
      },
      {
        rarity: 'UNCOMMON',
        mass: 5.5,
        structureCost: 13,
        basePrice: 630,
        scrapValue: 158,
        partHp: 40,
        pdf: 7,
        energyCont: -4,
        energyCombat: -10,
        specialProp: { idlePower: 4, armorPiercing: true },
      },
      {
        rarity: 'RARE',
        mass: 3.7,
        structureCost: 11,
        basePrice: 1250,
        scrapValue: 312,
        partHp: 50,
        pdf: 9,
        energyCont: -4,
        energyCombat: -10,
        specialProp: { idlePower: 4, armorPiercing: true },
      },
      {
        rarity: 'EPIC',
        mass: 3.7,
        structureCost: 9,
        basePrice: 2500,
        scrapValue: 625,
        partHp: 61,
        pdf: 11,
        energyCont: -4,
        energyCombat: -10,
        specialProp: { idlePower: 4, armorPiercing: true },
      },
      {
        rarity: 'LEGENDARY',
        mass: 1.8,
        structureCost: 9,
        basePrice: 5050,
        scrapValue: 1262,
        partHp: 76,
        pdf: 14,
        energyCont: -4,
        energyCombat: -10,
        specialProp: { idlePower: 4, armorPiercing: true },
      },
    ],
  },
  {
    base: 'weapon_missile',
    partClass: 'WEAPON',
    w: 1,
    h: 2,
    name: { en: 'Heavy Missile', 'pt-BR': 'Míssil Pesado' },
    description: {
      en: 'Heavy missiles: the highest firepower of any weapon, paid for in size (1×2), mass and price. Take it when you expect to fight.',
      'pt-BR':
        'Mísseis pesados: o maior poder de fogo entre as armas, pago em tamanho (1×2), massa e preço. Leve quando espera lutar.',
    },
    tiers: [
      {
        rarity: 'COMMON',
        mass: 8.6,
        structureCost: 11,
        basePrice: 170,
        scrapValue: 42,
        partHp: 17,
        pdf: 5,
        energyCont: -2,
      },
      {
        rarity: 'UNCOMMON',
        mass: 7.2,
        structureCost: 10,
        basePrice: 300,
        scrapValue: 75,
        partHp: 21,
        pdf: 6,
        energyCont: -2,
      },
      {
        rarity: 'RARE',
        mass: 6,
        structureCost: 9,
        basePrice: 450,
        scrapValue: 113,
        partHp: 25,
        pdf: 8,
        energyCont: -2,
      },
      {
        rarity: 'EPIC',
        mass: 5,
        structureCost: 8,
        basePrice: 900,
        scrapValue: 225,
        partHp: 30,
        pdf: 10,
        energyCont: -2,
      },
      {
        rarity: 'LEGENDARY',
        mass: 4,
        structureCost: 7,
        basePrice: 1800,
        scrapValue: 450,
        partHp: 38,
        pdf: 12,
        energyCont: -2,
      },
    ],
  },
  {
    base: 'weapon_missile_battery',
    partClass: 'WEAPON',
    w: 2,
    h: 2,
    name: { en: 'Missile Battery', 'pt-BR': 'Bateria de Mísseis' },
    description: {
      en: 'A 2×2 missile battery: the heaviest firepower in the game, paid for in size, mass and price.',
      'pt-BR':
        'Uma bateria de mísseis 2×2: o maior poder de fogo do jogo, pago em tamanho, massa e preço.',
    },
    tiers: [
      {
        rarity: 'COMMON',
        mass: 15.9,
        structureCost: 21,
        basePrice: 370,
        scrapValue: 92,
        partHp: 31,
        pdf: 11,
        energyCont: -4,
      },
      {
        rarity: 'UNCOMMON',
        mass: 13.2,
        structureCost: 19,
        basePrice: 660,
        scrapValue: 165,
        partHp: 38,
        pdf: 14,
        energyCont: -4,
      },
      {
        rarity: 'RARE',
        mass: 11,
        structureCost: 17,
        basePrice: 990,
        scrapValue: 248,
        partHp: 45,
        pdf: 18,
        energyCont: -4,
      },
      {
        rarity: 'EPIC',
        mass: 9.2,
        structureCost: 15,
        basePrice: 2000,
        scrapValue: 500,
        partHp: 54,
        pdf: 22,
        energyCont: -4,
      },
      {
        rarity: 'LEGENDARY',
        mass: 7.4,
        structureCost: 13,
        basePrice: 3950,
        scrapValue: 988,
        partHp: 68,
        pdf: 26,
        energyCont: -4,
      },
    ],
  },
  {
    base: 'weapon_missile_light',
    partClass: 'WEAPON',
    w: 1,
    h: 1,
    name: { en: 'Light Missile', 'pt-BR': 'Míssil Leve' },
    description: {
      en: 'A single-cell missile launcher: a little of the missile punch in a small package.',
      'pt-BR':
        'Um lançador de mísseis de uma célula: um pouco do impacto dos mísseis em um pacote pequeno.',
    },
    tiers: [
      {
        rarity: 'COMMON',
        mass: 4.8,
        structureCost: 6,
        basePrice: 75,
        scrapValue: 19,
        partHp: 9,
        pdf: 2,
        energyCont: -1,
      },
      {
        rarity: 'UNCOMMON',
        mass: 4,
        structureCost: 6,
        basePrice: 140,
        scrapValue: 35,
        partHp: 11,
        pdf: 3,
        energyCont: -1,
      },
      {
        rarity: 'RARE',
        mass: 3.3,
        structureCost: 5,
        basePrice: 200,
        scrapValue: 50,
        partHp: 13,
        pdf: 4,
        energyCont: -1,
      },
      {
        rarity: 'EPIC',
        mass: 2.8,
        structureCost: 4,
        basePrice: 400,
        scrapValue: 100,
        partHp: 16,
        pdf: 4,
        energyCont: -1,
      },
      {
        rarity: 'LEGENDARY',
        mass: 2.2,
        structureCost: 4,
        basePrice: 810,
        scrapValue: 202,
        partHp: 20,
        pdf: 5,
        energyCont: -1,
      },
    ],
  },
  {
    base: 'armor_plate',
    partClass: 'DEFENSE',
    w: 2,
    h: 1,
    name: { en: 'Armor Plate', 'pt-BR': 'Placa de Armadura' },
    description: {
      en: 'Heavy armor plating. Cuts every hit that gets past the shield by a flat amount, then soaks the rest until it is spent. Heavy and dear, for fighters and dangerous space; few hit points of its own.',
      'pt-BR':
        'Blindagem pesada. Corta todo golpe que passa do escudo em uma quantia fixa e depois absorve o resto até se esgotar. Pesada e cara, para combatentes e espaço perigoso; poucos pontos de vida próprios.',
    },
    tiers: [
      {
        rarity: 'COMMON',
        mass: 12.5,
        structureCost: 14,
        basePrice: 250,
        scrapValue: 62,
        partHp: 19,
        bli: 3,
      },
      {
        rarity: 'UNCOMMON',
        mass: 10,
        structureCost: 12,
        basePrice: 500,
        scrapValue: 125,
        partHp: 24,
        bli: 4,
      },
      {
        rarity: 'RARE',
        mass: 8,
        structureCost: 10,
        basePrice: 1000,
        scrapValue: 250,
        partHp: 31,
        bli: 5,
        name: { en: 'Composite Armor Plate', 'pt-BR': 'Placa de Armadura Composta' },
        description: {
          en: 'Advanced layered armor: cuts more of every hit and soaks more punishment than standard plating, a little lighter.',
          'pt-BR':
            'Blindagem avançada em camadas: corta mais de cada golpe e absorve mais castigo que a placa padrão, um pouco mais leve.',
        },
      },
      {
        rarity: 'EPIC',
        mass: 6,
        structureCost: 8,
        basePrice: 2000,
        scrapValue: 500,
        partHp: 38,
        bli: 6,
        name: { en: 'Ablative Armor Plate', 'pt-BR': 'Placa de Armadura Ablativa' },
        description: {
          en: 'A heavy armor plate with regenerative layering: cuts and soaks far more than a basic plate, with less mass and structure cost.',
          'pt-BR':
            'Uma placa de blindagem pesada com camadas regenerativas: corta e absorve muito mais que a básica, com menos massa e custo de estrutura.',
        },
      },
      {
        rarity: 'LEGENDARY',
        mass: 6,
        structureCost: 8,
        basePrice: 4000,
        scrapValue: 1000,
        partHp: 48,
        bli: 8,
        name: { en: 'Titan Plate', 'pt-BR': 'Placa de Titã' },
        description: {
          en: 'A legendary armor slab forged from ultra-dense alloy. It cuts and soaks blows that would vaporize lesser plating.',
          'pt-BR':
            'Uma laje de blindagem lendária forjada em liga ultradensa. Corta e absorve golpes que vaporizariam placas inferiores.',
        },
      },
    ],
  },
  {
    base: 'armor_plate_large',
    partClass: 'DEFENSE',
    w: 2,
    h: 2,
    name: { en: 'Heavy Armor Plate', 'pt-BR': 'Placa de Armadura Pesada' },
    description: {
      en: 'A 2×2 armor plate: the most protection per cell, and the weight to match.',
      'pt-BR': 'Uma placa de armadura 2×2: a maior proteção por célula, com o peso correspondente.',
    },
    tiers: [
      {
        rarity: 'COMMON',
        mass: 23,
        structureCost: 26,
        basePrice: 580,
        scrapValue: 145,
        partHp: 33,
        bli: 7.5,
      },
      {
        rarity: 'UNCOMMON',
        mass: 18.4,
        structureCost: 22,
        basePrice: 1150,
        scrapValue: 288,
        partHp: 43,
        bli: 9,
      },
      {
        rarity: 'RARE',
        mass: 14.7,
        structureCost: 18,
        basePrice: 2300,
        scrapValue: 575,
        partHp: 56,
        bli: 11.5,
      },
      {
        rarity: 'EPIC',
        mass: 11,
        structureCost: 15,
        basePrice: 4600,
        scrapValue: 1150,
        partHp: 68,
        bli: 14,
      },
      {
        rarity: 'LEGENDARY',
        mass: 11,
        structureCost: 15,
        basePrice: 9200,
        scrapValue: 2300,
        partHp: 86,
        bli: 18.5,
      },
    ],
  },
  {
    base: 'armor_plate_small',
    partClass: 'DEFENSE',
    w: 1,
    h: 1,
    name: { en: 'Light Armor Plate', 'pt-BR': 'Placa de Armadura Leve' },
    description: {
      en: 'A single-cell armor plate: less protection than a full plate, but it fits anywhere.',
      'pt-BR':
        'Uma placa de armadura de uma célula: menos proteção que a placa inteira, mas cabe em qualquer lugar.',
    },
    tiers: [
      {
        rarity: 'COMMON',
        mass: 6.9,
        structureCost: 8,
        basePrice: 120,
        scrapValue: 30,
        partHp: 10,
        bli: 1.5,
      },
      {
        rarity: 'UNCOMMON',
        mass: 5.5,
        structureCost: 7,
        basePrice: 240,
        scrapValue: 60,
        partHp: 13,
        bli: 2,
      },
      {
        rarity: 'RARE',
        mass: 4.4,
        structureCost: 6,
        basePrice: 480,
        scrapValue: 120,
        partHp: 16,
        bli: 2.5,
      },
      {
        rarity: 'EPIC',
        mass: 3.3,
        structureCost: 4,
        basePrice: 950,
        scrapValue: 238,
        partHp: 20,
        bli: 3,
      },
      {
        rarity: 'LEGENDARY',
        mass: 3.3,
        structureCost: 4,
        basePrice: 1900,
        scrapValue: 475,
        partHp: 25,
        bli: 4,
      },
    ],
  },
  {
    base: 'hull',
    partClass: 'DEFENSE',
    w: 2,
    h: 1,
    name: { en: 'Hull Frame', 'pt-BR': 'Estrutura de Casco' },
    description: {
      en: 'A cheap, light structural frame: plenty of hit points, but no armor at all. Hit points keep the ship alive once armor and shield are gone.',
      'pt-BR':
        'Uma estrutura barata e leve: muitos pontos de vida, mas nenhuma blindagem. Os pontos de vida mantêm a nave viva quando a blindagem e o escudo acabam.',
    },
    tiers: [
      { rarity: 'COMMON', mass: 4, structureCost: 5, basePrice: 100, scrapValue: 25, partHp: 30 },
      {
        rarity: 'UNCOMMON',
        mass: 4,
        structureCost: 4,
        basePrice: 200,
        scrapValue: 50,
        partHp: 39,
        name: { en: 'Reinforced Hull Frame', 'pt-BR': 'Estrutura de Casco Reforçada' },
        description: {
          en: 'A stronger structural frame with more hit points than a basic hull, still no armor and no heavier.',
          'pt-BR':
            'Uma estrutura mais forte, com mais pontos de vida que o casco básico, ainda sem blindagem e sem mais peso.',
        },
      },
      {
        rarity: 'RARE',
        mass: 3,
        structureCost: 4,
        basePrice: 400,
        scrapValue: 100,
        partHp: 51,
        name: { en: 'Composite Hull Frame', 'pt-BR': 'Estrutura de Casco Composta' },
        description: {
          en: 'An advanced composite frame that is lighter and holds far more hit points than standard hull plating. No armor.',
          'pt-BR':
            'Uma estrutura composta avançada, mais leve e com muito mais pontos de vida que o casco padrão. Sem blindagem.',
        },
      },
      {
        rarity: 'EPIC',
        mass: 3,
        structureCost: 3,
        basePrice: 800,
        scrapValue: 200,
        partHp: 60,
        name: { en: 'Titanium Hull Frame', 'pt-BR': 'Estrutura de Casco de Titânio' },
        description: {
          en: 'A heavy-duty hull frame with military-grade structure: a great many hit points for little weight. No armor.',
          'pt-BR':
            'Uma estrutura reforçada de padrão militar: muitíssimos pontos de vida por pouco peso. Sem blindagem.',
        },
      },
      {
        rarity: 'LEGENDARY',
        mass: 2,
        structureCost: 3,
        basePrice: 1600,
        scrapValue: 400,
        partHp: 75,
        name: { en: 'Aegis Hull Frame', 'pt-BR': 'Estrutura de Casco Aegis' },
        description: {
          en: 'A legendary hull frame. Its woven alloy shell holds more hit points than any other frame, yet it is remarkably light. No armor.',
          'pt-BR':
            'Uma estrutura lendária. Sua casca de liga trançada guarda mais pontos de vida que qualquer outra, e é notavelmente leve. Sem blindagem.',
        },
      },
    ],
  },
  {
    base: 'hull_large',
    partClass: 'DEFENSE',
    w: 2,
    h: 2,
    name: { en: 'Heavy Hull Frame', 'pt-BR': 'Estrutura de Casco Pesada' },
    description: {
      en: 'A 2×2 hull frame: more hit points per cell and per credit than the standard frame.',
      'pt-BR':
        'Uma estrutura de casco 2×2: mais pontos de vida por célula e por crédito que a estrutura padrão.',
    },
    tiers: [
      { rarity: 'COMMON', mass: 7.4, structureCost: 9, basePrice: 230, scrapValue: 58, partHp: 69 },
      {
        rarity: 'UNCOMMON',
        mass: 7.4,
        structureCost: 7,
        basePrice: 460,
        scrapValue: 115,
        partHp: 90,
      },
      { rarity: 'RARE', mass: 5.5, structureCost: 7, basePrice: 920, scrapValue: 230, partHp: 117 },
      {
        rarity: 'EPIC',
        mass: 5.5,
        structureCost: 6,
        basePrice: 1850,
        scrapValue: 462,
        partHp: 138,
      },
      {
        rarity: 'LEGENDARY',
        mass: 3.7,
        structureCost: 6,
        basePrice: 3700,
        scrapValue: 925,
        partHp: 172,
      },
    ],
  },
  {
    base: 'hull_small',
    partClass: 'DEFENSE',
    w: 1,
    h: 1,
    name: { en: 'Light Hull Frame', 'pt-BR': 'Estrutura de Casco Leve' },
    description: {
      en: 'A single-cell hull frame: cheap structure that slots into any gap.',
      'pt-BR':
        'Uma estrutura de casco de uma célula: estrutura barata que encaixa em qualquer vão.',
    },
    tiers: [
      { rarity: 'COMMON', mass: 2.2, structureCost: 3, basePrice: 50, scrapValue: 12, partHp: 14 },
      {
        rarity: 'UNCOMMON',
        mass: 2.2,
        structureCost: 2,
        basePrice: 95,
        scrapValue: 24,
        partHp: 19,
      },
      { rarity: 'RARE', mass: 1.7, structureCost: 2, basePrice: 190, scrapValue: 48, partHp: 24 },
      { rarity: 'EPIC', mass: 1.7, structureCost: 2, basePrice: 380, scrapValue: 95, partHp: 28 },
      {
        rarity: 'LEGENDARY',
        mass: 1.1,
        structureCost: 2,
        basePrice: 760,
        scrapValue: 190,
        partHp: 36,
      },
    ],
  },
  {
    base: 'shield_basic',
    partClass: 'DEFENSE',
    w: 1,
    h: 1,
    name: { en: 'Basic Shield', 'pt-BR': 'Escudo Básico' },
    description: {
      en: 'An energy shield: absorbs damage first and recharges between rounds of a fight. Draws combat energy, so it needs a battery. Great against pirates; useless if the battery cannot power it.',
      'pt-BR':
        'Um escudo de energia: absorve o dano primeiro e recarrega entre as rodadas da luta. Consome energia de combate, então precisa de bateria. Ótimo contra piratas; inútil se a bateria não conseguir alimentá-lo.',
    },
    tiers: [
      {
        rarity: 'COMMON',
        mass: 5.3,
        structureCost: 8,
        basePrice: 200,
        scrapValue: 50,
        partHp: 18,
        esc: 11,
        energyCont: -2,
        energyCombat: -7,
        specialProp: { shieldRegen: 3 },
      },
      {
        rarity: 'UNCOMMON',
        mass: 4,
        structureCost: 7,
        basePrice: 400,
        scrapValue: 100,
        partHp: 25,
        esc: 14,
        energyCont: -2,
        energyCombat: -6,
        specialProp: { shieldRegen: 3 },
      },
      {
        rarity: 'RARE',
        mass: 3,
        structureCost: 6,
        basePrice: 800,
        scrapValue: 200,
        partHp: 34,
        esc: 18,
        energyCont: -2,
        energyCombat: -5,
        specialProp: { shieldRegen: 4 },
        name: { en: 'Reinforced Shield', 'pt-BR': 'Escudo Reforçado' },
        description: {
          en: 'A stronger energy shield with faster recharge. Absorbs more damage than a basic shield while drawing slightly less energy.',
          'pt-BR':
            'Um escudo de energia mais forte com recarga mais rápida. Absorve mais dano que um escudo básico consumindo um pouco menos de energia.',
        },
      },
      {
        rarity: 'EPIC',
        mass: 3,
        structureCost: 5,
        basePrice: 1600,
        scrapValue: 400,
        partHp: 44,
        esc: 24,
        energyCont: -2,
        energyCombat: -5,
        specialProp: { shieldRegen: 5 },
        name: { en: 'Heavy Shield Generator', 'pt-BR': 'Gerador de Escudo Pesado' },
        description: {
          en: 'A compact shield generator with double the absorption of a basic model. Fits in the same 1×1 slot and costs less structure.',
          'pt-BR':
            'Um gerador de escudo compacto com o dobro de absorção do modelo básico. Cabe no mesmo slot 1×1 e custa menos estrutura.',
        },
      },
      {
        rarity: 'LEGENDARY',
        mass: 2,
        structureCost: 4,
        basePrice: 3200,
        scrapValue: 800,
        partHp: 56,
        esc: 32,
        energyCont: -2,
        energyCombat: -4,
        specialProp: { shieldRegen: 6 },
        name: { en: 'Aegis Shield', 'pt-BR': 'Escudo Aegis' },
        description: {
          en: 'A legendary shield that turns aside almost anything. Its regenerative field absorbs massive punishment for minimal energy.',
          'pt-BR':
            'Um escudo lendário que desvia quase tudo. Seu campo regenerativo absorve punição massiva com energia mínima.',
        },
      },
    ],
  },
  {
    base: 'shield_large',
    partClass: 'DEFENSE',
    w: 2,
    h: 2,
    name: { en: 'Fortress Shield', 'pt-BR': 'Escudo Fortaleza' },
    description: {
      en: 'A 2×2 shield array for big ships: the deepest shield pool and the fastest recovery, at a heavy power cost.',
      'pt-BR':
        'Uma matriz de escudo 2×2 para naves grandes: o maior escudo e a recuperação mais rápida, com alto custo de energia.',
    },
    tiers: [
      {
        rarity: 'COMMON',
        mass: 19.6,
        structureCost: 30,
        basePrice: 1050,
        scrapValue: 262,
        partHp: 66,
        esc: 57,
        energyCont: -8,
        energyCombat: -29,
        specialProp: { shieldRegen: 16 },
      },
      {
        rarity: 'UNCOMMON',
        mass: 14.7,
        structureCost: 26,
        basePrice: 2100,
        scrapValue: 525,
        partHp: 90,
        esc: 73,
        energyCont: -8,
        energyCombat: -24,
        specialProp: { shieldRegen: 16 },
      },
      {
        rarity: 'RARE',
        mass: 11,
        structureCost: 22,
        basePrice: 4150,
        scrapValue: 1038,
        partHp: 122,
        esc: 94,
        energyCont: -8,
        energyCombat: -20,
        specialProp: { shieldRegen: 21 },
      },
      {
        rarity: 'EPIC',
        mass: 11,
        structureCost: 18,
        basePrice: 8300,
        scrapValue: 2075,
        partHp: 158,
        esc: 125,
        energyCont: -8,
        energyCombat: -20,
        specialProp: { shieldRegen: 26 },
      },
      {
        rarity: 'LEGENDARY',
        mass: 7.4,
        structureCost: 15,
        basePrice: 16650,
        scrapValue: 4162,
        partHp: 202,
        esc: 166,
        energyCont: -8,
        energyCombat: -16,
        specialProp: { shieldRegen: 31 },
      },
    ],
  },
  {
    base: 'shield_medium',
    partClass: 'DEFENSE',
    w: 1,
    h: 2,
    name: { en: 'Shield Generator', 'pt-BR': 'Gerador de Escudo' },
    description: {
      en: 'A 1×2 shield generator: a bigger bubble and faster recovery than the basic emitter, for more power.',
      'pt-BR':
        'Um gerador de escudo 1×2: uma bolha maior e recuperação mais rápida que o emissor básico, por mais energia.',
    },
    tiers: [
      {
        rarity: 'COMMON',
        mass: 9.8,
        structureCost: 15,
        basePrice: 460,
        scrapValue: 115,
        partHp: 33,
        esc: 25,
        energyCont: -4,
        energyCombat: -14,
        specialProp: { shieldRegen: 7 },
      },
      {
        rarity: 'UNCOMMON',
        mass: 7.4,
        structureCost: 13,
        basePrice: 920,
        scrapValue: 230,
        partHp: 45,
        esc: 32,
        energyCont: -4,
        energyCombat: -12,
        specialProp: { shieldRegen: 7 },
      },
      {
        rarity: 'RARE',
        mass: 5.5,
        structureCost: 11,
        basePrice: 1850,
        scrapValue: 462,
        partHp: 61,
        esc: 41,
        energyCont: -4,
        energyCombat: -10,
        specialProp: { shieldRegen: 9 },
      },
      {
        rarity: 'EPIC',
        mass: 5.5,
        structureCost: 9,
        basePrice: 3700,
        scrapValue: 925,
        partHp: 79,
        esc: 55,
        energyCont: -4,
        energyCombat: -10,
        specialProp: { shieldRegen: 12 },
      },
      {
        rarity: 'LEGENDARY',
        mass: 3.7,
        structureCost: 7,
        basePrice: 7350,
        scrapValue: 1838,
        partHp: 101,
        esc: 74,
        energyCont: -4,
        energyCombat: -8,
        specialProp: { shieldRegen: 14 },
      },
    ],
  },
  {
    base: 'cargo',
    partClass: 'CARGO',
    w: 1,
    h: 1,
    name: { en: 'Cargo Hold', 'pt-BR': 'Compartimento de Carga' },
    description: {
      en: 'Cargo space. Each hold adds capacity for deliveries, so more holds mean bigger, better-paid jobs. Adds mass, which slows the ship.',
      'pt-BR':
        'Espaço de carga. Cada compartimento aumenta a capacidade para entregas, então mais compartimentos significam trabalhos maiores e mais bem pagos. Adiciona massa, o que deixa a nave mais lenta.',
    },
    tiers: [
      {
        rarity: 'COMMON',
        mass: 2,
        structureCost: 4,
        basePrice: 80,
        scrapValue: 20,
        partHp: 15,
        crg: 5,
      },
      {
        rarity: 'UNCOMMON',
        mass: 2,
        structureCost: 3,
        basePrice: 150,
        scrapValue: 38,
        partHp: 20,
        crg: 6,
        name: { en: 'Reinforced Cargo Hold', 'pt-BR': 'Compartimento de Carga Reforçado' },
        description: {
          en: 'A sturdier cargo hold with slightly more capacity. Uses the same 1×1 space as a basic hold but costs less structure.',
          'pt-BR':
            'Um compartimento de carga mais resistente com um pouco mais de capacidade. Usa o mesmo espaço 1×1 de um compartimento básico, mas custa menos estrutura.',
        },
      },
      {
        rarity: 'RARE',
        mass: 1,
        structureCost: 3,
        basePrice: 300,
        scrapValue: 75,
        partHp: 25,
        crg: 8,
        name: { en: 'Expanded Cargo Hold', 'pt-BR': 'Compartimento de Carga Expandido' },
        description: {
          en: 'A lightweight cargo hold with more capacity than the basic model. Advanced materials cut both mass and structure cost.',
          'pt-BR':
            'Um compartimento de carga leve com mais capacidade que o modelo básico. Materiais avançados reduzem massa e custo de estrutura.',
        },
      },
      {
        rarity: 'EPIC',
        mass: 1,
        structureCost: 2,
        basePrice: 600,
        scrapValue: 150,
        partHp: 30,
        crg: 10,
        name: { en: 'High-Capacity Hold', 'pt-BR': 'Compartimento de Alta Capacidade' },
        description: {
          en: 'A compact freight bay that holds twice as much cargo as a basic hold. Fits in a featherweight 1×1 frame.',
          'pt-BR':
            'Um compartimento de carga compacto que guarda o dobro de carga de um compartimento básico. Cabe num minúsculo quadro 1×1.',
        },
      },
      {
        rarity: 'LEGENDARY',
        mass: 1,
        structureCost: 2,
        basePrice: 1200,
        scrapValue: 300,
        partHp: 38,
        crg: 13,
        name: { en: 'Void-Fold Cargo Bay', 'pt-BR': 'Baía de Carga de Dobra do Vazio' },
        description: {
          en: 'A legendary freight module. Its compressed storage lattice fits a small freighter’s worth of cargo into a single 1×1 slot.',
          'pt-BR':
            'Um módulo de carga lendário. Sua malha de armazenamento comprimido cabe a carga de um pequeno cargueiro num único slot 1×1.',
        },
      },
    ],
  },
  {
    base: 'cargo_bay',
    partClass: 'CARGO',
    w: 2,
    h: 2,
    name: { en: 'Cargo Bay', 'pt-BR': 'Baía de Carga' },
    description: {
      en: 'A 2×2 cargo bay for freighters: the most room per cell and per credit.',
      'pt-BR': 'Uma baía de carga 2×2 para cargueiros: o maior espaço por célula e por crédito.',
    },
    tiers: [
      {
        rarity: 'COMMON',
        mass: 7.4,
        structureCost: 15,
        basePrice: 400,
        scrapValue: 100,
        partHp: 54,
        crg: 25,
      },
      {
        rarity: 'UNCOMMON',
        mass: 7.4,
        structureCost: 11,
        basePrice: 750,
        scrapValue: 188,
        partHp: 72,
        crg: 30,
      },
      {
        rarity: 'RARE',
        mass: 3.7,
        structureCost: 11,
        basePrice: 1500,
        scrapValue: 375,
        partHp: 90,
        crg: 40,
      },
      {
        rarity: 'EPIC',
        mass: 3.7,
        structureCost: 7,
        basePrice: 3000,
        scrapValue: 750,
        partHp: 108,
        crg: 50,
      },
      {
        rarity: 'LEGENDARY',
        mass: 3.7,
        structureCost: 7,
        basePrice: 6000,
        scrapValue: 1500,
        partHp: 137,
        crg: 65,
      },
    ],
  },
  {
    base: 'cargo_large',
    partClass: 'CARGO',
    w: 1,
    h: 2,
    name: { en: 'Large Cargo Hold', 'pt-BR': 'Compartimento de Carga Grande' },
    description: {
      en: 'A 1×2 cargo hold: more room per cell than the standard hold.',
      'pt-BR': 'Um compartimento de carga 1×2: mais espaço por célula que o compartimento padrão.',
    },
    tiers: [
      {
        rarity: 'COMMON',
        mass: 3.7,
        structureCost: 7,
        basePrice: 180,
        scrapValue: 45,
        partHp: 27,
        crg: 11,
      },
      {
        rarity: 'UNCOMMON',
        mass: 3.7,
        structureCost: 6,
        basePrice: 330,
        scrapValue: 82,
        partHp: 36,
        crg: 13,
      },
      {
        rarity: 'RARE',
        mass: 1.8,
        structureCost: 6,
        basePrice: 660,
        scrapValue: 165,
        partHp: 45,
        crg: 18,
      },
      {
        rarity: 'EPIC',
        mass: 1.8,
        structureCost: 4,
        basePrice: 1300,
        scrapValue: 325,
        partHp: 54,
        crg: 22,
      },
      {
        rarity: 'LEGENDARY',
        mass: 1.8,
        structureCost: 4,
        basePrice: 2650,
        scrapValue: 662,
        partHp: 68,
        crg: 29,
      },
    ],
  },
  {
    base: 'passenger_cabin',
    partClass: 'CARGO',
    w: 1,
    h: 2,
    name: { en: 'Passenger Cabin', 'pt-BR': 'Cabine de Passageiros' },
    description: {
      en: 'A pressurized cabin for people instead of freight. Transport missions need one, and so do some rescues. It only works together with a Life Support module, and adds mass.',
      'pt-BR':
        'Uma cabine pressurizada para pessoas em vez de carga. Missões de transporte precisam de uma, e alguns resgates também. Só funciona junto com um módulo de Suporte de Vida e adiciona massa.',
    },
    tiers: [
      {
        rarity: 'COMMON',
        mass: 6,
        structureCost: 8,
        basePrice: 260,
        scrapValue: 60,
        partHp: 25,
        energyCont: -2,
        specialProp: { pressurized: true },
      },
      {
        rarity: 'UNCOMMON',
        mass: 5,
        structureCost: 7,
        basePrice: 400,
        scrapValue: 100,
        partHp: 32,
        energyCont: -2,
        specialProp: { pressurized: true },
        name: { en: 'Comfortable Cabin', 'pt-BR': 'Cabine Confortável' },
        description: {
          en: 'A better pressurized cabin with improved life-support coupling. Lighter and cheaper on structure than a basic cabin.',
          'pt-BR':
            'Uma cabine pressurizada melhor com acoplamento de suporte de vida aprimorado. Mais leve e mais barata em estrutura que uma cabine básica.',
        },
      },
      {
        rarity: 'RARE',
        mass: 4,
        structureCost: 6,
        basePrice: 650,
        scrapValue: 163,
        partHp: 40,
        energyCont: -2,
        specialProp: { pressurized: true },
        name: { en: 'Reinforced Passenger Cabin', 'pt-BR': 'Cabine de Passageiros Reforçada' },
        description: {
          en: 'A sturdy cabin for valuable passengers. Stronger hull and lower power draw than lower-tier cabins.',
          'pt-BR':
            'Uma cabine resistente para passageiros valiosos. Casco mais forte e consumo de energia menor que cabines de tiers inferiores.',
        },
      },
      {
        rarity: 'EPIC',
        mass: 3,
        structureCost: 5,
        basePrice: 1000,
        scrapValue: 250,
        partHp: 50,
        specialProp: { pressurized: true },
        name: { en: 'Luxury Transport Module', 'pt-BR': 'Módulo de Transporte de Luxo' },
        description: {
          en: 'A compact luxury cabin for high-paying passengers. Much lighter and cheaper on structure than a basic cabin.',
          'pt-BR':
            'Uma cabine de luxo compacta para passageiros que pagam bem. Muito mais leve e mais barata em estrutura que uma cabine básica.',
        },
      },
      {
        rarity: 'LEGENDARY',
        mass: 2,
        structureCost: 4,
        basePrice: 1600,
        scrapValue: 400,
        partHp: 62,
        specialProp: { pressurized: true },
        name: { en: 'Cryo-Sleep Bay', 'pt-BR': 'Baía de Sono Criogênico' },
        description: {
          en: 'A legendary passenger module. Passengers sleep through the journey in safety, using almost no life-support power.',
          'pt-BR':
            'Um módulo de passageiros lendário. Passageiros dormem durante a viagem em segurança, usando quase nenhuma energia de suporte de vida.',
        },
      },
    ],
  },
  {
    base: 'sensor_radar',
    partClass: 'SENSOR',
    w: 1,
    h: 1,
    name: { en: 'Radar', 'pt-BR': 'Radar' },
    description: {
      en: 'Long-range sensors that spot ambushes before they happen, lowering the chance of being caught by pirates. Draws a little power all the time.',
      'pt-BR':
        'Sensores de longo alcance que detectam emboscadas antes que aconteçam, reduzindo a chance de ser pego por piratas. Consome um pouco de energia o tempo todo.',
    },
    tiers: [
      {
        rarity: 'COMMON',
        mass: 2,
        structureCost: 4,
        basePrice: 200,
        scrapValue: 50,
        partHp: 15,
        sen: 4,
        energyCont: -4,
      },
      {
        rarity: 'UNCOMMON',
        mass: 2,
        structureCost: 3,
        basePrice: 350,
        scrapValue: 88,
        partHp: 20,
        sen: 6,
        energyCont: -4,
        name: { en: 'Enhanced Radar', 'pt-BR': 'Radar Aprimorado' },
        description: {
          en: 'A tuned sensor array with better range and clearer signatures. Spots ambushes more reliably than a basic radar.',
          'pt-BR':
            'Uma matriz de sensores sintonizada com maior alcance e assinaturas mais claras. Detecta emboscadas com mais confiança que um radar básico.',
        },
      },
      {
        rarity: 'RARE',
        mass: 1,
        structureCost: 3,
        basePrice: 600,
        scrapValue: 150,
        partHp: 26,
        sen: 8,
        energyCont: -2,
        name: { en: 'Long-Range Scanner', 'pt-BR': 'Scanner de Longo Alcance' },
        description: {
          en: 'A lightweight scanner with extended detection range. Uses less power and structure than lower-tier sensors.',
          'pt-BR':
            'Um scanner leve com alcance de detecção estendido. Usa menos energia e estrutura que sensores de tiers inferiores.',
        },
      },
      {
        rarity: 'EPIC',
        mass: 1,
        structureCost: 2,
        basePrice: 1000,
        scrapValue: 250,
        partHp: 30,
        sen: 12,
        energyCont: -2,
        name: { en: 'Wide-Band Sensor Array', 'pt-BR': 'Matriz de Sensores de Banda Larga' },
        description: {
          en: 'A multi-spectrum array that triples the detection power of a basic radar. Almost no pirate ambush escapes its notice.',
          'pt-BR':
            'Uma matriz multiespectro que triplica o poder de detecção de um radar básico. Quase nenhuma emboscada pirata escapa ao seu alcance.',
        },
      },
      {
        rarity: 'LEGENDARY',
        mass: 1,
        structureCost: 2,
        basePrice: 1600,
        scrapValue: 400,
        partHp: 38,
        sen: 16,
        energyCont: -2,
        name: { en: 'Omniscience Suite', 'pt-BR': 'Suíte de Onisciência' },
        description: {
          en: 'A legendary sensor suite. Its predictive algorithms spot threats before they even form, making ambushes nearly impossible.',
          'pt-BR':
            'Uma suíte de sensores lendária. Seus algoritmos preditivos detectam ameaças antes mesmo de se formarem, tornando emboscadas quase impossíveis.',
        },
      },
    ],
  },
  {
    base: 'sensor_radar_large',
    partClass: 'SENSOR',
    w: 1,
    h: 2,
    name: { en: 'Wide Radar', 'pt-BR': 'Radar de Banda Larga' },
    description: {
      en: 'A 1×2 radar with a longer reach than the standard unit, for more power.',
      'pt-BR': 'Um radar 1×2 com alcance maior que a unidade padrão, por mais energia.',
    },
    tiers: [
      {
        rarity: 'COMMON',
        mass: 3.7,
        structureCost: 7,
        basePrice: 480,
        scrapValue: 120,
        partHp: 27,
        sen: 10,
        energyCont: -8,
      },
      {
        rarity: 'UNCOMMON',
        mass: 3.7,
        structureCost: 6,
        basePrice: 840,
        scrapValue: 210,
        partHp: 36,
        sen: 14,
        energyCont: -8,
      },
      {
        rarity: 'RARE',
        mass: 1.8,
        structureCost: 6,
        basePrice: 1450,
        scrapValue: 362,
        partHp: 47,
        sen: 19,
        energyCont: -4,
      },
      {
        rarity: 'EPIC',
        mass: 1.8,
        structureCost: 4,
        basePrice: 2400,
        scrapValue: 600,
        partHp: 54,
        sen: 29,
        energyCont: -4,
      },
      {
        rarity: 'LEGENDARY',
        mass: 1.8,
        structureCost: 4,
        basePrice: 3850,
        scrapValue: 962,
        partHp: 68,
        sen: 38,
        energyCont: -4,
      },
    ],
  },
  {
    base: 'life_support',
    partClass: 'UTILITY',
    w: 1,
    h: 1,
    name: { en: 'Life Support', 'pt-BR': 'Suporte de Vida' },
    description: {
      en: 'Air, heat and water for everyone aboard. Any ship with a Passenger Cabin must carry one or it is not allowed to fly. Draws steady power all the time.',
      'pt-BR':
        'Ar, calor e água para todos a bordo. Toda nave com uma Cabine de Passageiros precisa carregar um, senão não pode voar. Consome energia constante o tempo todo.',
    },
    tiers: [
      {
        rarity: 'COMMON',
        mass: 3,
        structureCost: 4,
        basePrice: 300,
        scrapValue: 70,
        partHp: 15,
        energyCont: -6,
        specialProp: { lifeSupport: true },
      },
      {
        rarity: 'UNCOMMON',
        mass: 3,
        structureCost: 3,
        basePrice: 400,
        scrapValue: 100,
        partHp: 20,
        energyCont: -4,
        specialProp: { lifeSupport: true },
        name: { en: 'Efficient Life Support', 'pt-BR': 'Suporte de Vida Eficiente' },
        description: {
          en: 'A more efficient life-support loop. Keeps the same crew alive while drawing less power and costing less structure.',
          'pt-BR':
            'Um ciclo de suporte de vida mais eficiente. Mantém a mesma tripulação viva consumindo menos energia e custando menos estrutura.',
        },
      },
      {
        rarity: 'RARE',
        mass: 2,
        structureCost: 3,
        basePrice: 560,
        scrapValue: 140,
        partHp: 26,
        energyCont: -4,
        specialProp: { lifeSupport: true },
        name: { en: 'Recycling Life Support', 'pt-BR': 'Suporte de Vida Reciclável' },
        description: {
          en: 'A closed-loop system that recycles air and water. Lighter and cheaper on structure than basic life support.',
          'pt-BR':
            'Um sistema de ciclo fechado que recicla ar e água. Mais leve e mais barato em estrutura que o suporte de vida básico.',
        },
      },
      {
        rarity: 'EPIC',
        mass: 2,
        structureCost: 2,
        basePrice: 800,
        scrapValue: 200,
        partHp: 30,
        energyCont: -2,
        specialProp: { lifeSupport: true },
        name: { en: 'Regenerative Life Support', 'pt-BR': 'Suporte de Vida Regenerativo' },
        description: {
          en: 'An advanced life-support unit. It uses a fraction of the power of a basic system while keeping the crew safe in a compact frame.',
          'pt-BR':
            'Uma unidade avançada de suporte de vida. Usa uma fração da energia de um sistema básico enquanto mantém a tripulação segura num quadro compacto.',
        },
      },
      {
        rarity: 'LEGENDARY',
        mass: 1,
        structureCost: 2,
        basePrice: 1200,
        scrapValue: 300,
        partHp: 38,
        energyCont: -2,
        specialProp: { lifeSupport: true },
        name: { en: 'Bio-Dome Core', 'pt-BR': 'Núcleo de Biodomo' },
        description: {
          en: 'A legendary self-sustaining life-support core. It barely draws power and can keep a whole crew alive indefinitely.',
          'pt-BR':
            'Um núcleo lendário de suporte de vida autossustentável. Consome quase nenhuma energia e mantém uma tripulação inteira viva indefinidamente.',
        },
      },
    ],
  },
  {
    base: 'mining_rig',
    partClass: 'UTILITY',
    w: 1,
    h: 2,
    name: { en: 'Mining Rig', 'pt-BR': 'Plataforma de Mineração' },
    description: {
      en: 'An automated extractor. Needed for mining missions and for pulling ore out of asteroid fields, which you sell at ports. Draws steady power and adds mass.',
      'pt-BR':
        'Um extrator automático. Necessária para missões de mineração e para tirar minério de campos de asteroides, que você vende nos portos. Consome energia constante e adiciona massa.',
    },
    tiers: [
      {
        rarity: 'COMMON',
        mass: 10.7,
        structureCost: 12,
        basePrice: 200,
        scrapValue: 50,
        partHp: 18,
        min: 1,
        energyCont: -6,
      },
      {
        rarity: 'UNCOMMON',
        mass: 8,
        structureCost: 10,
        basePrice: 400,
        scrapValue: 100,
        partHp: 25,
        min: 1.5,
        energyCont: -6,
      },
      {
        rarity: 'RARE',
        mass: 6,
        structureCost: 8,
        basePrice: 800,
        scrapValue: 200,
        partHp: 34,
        min: 2,
        energyCont: -6,
        name: { en: 'Heavy Mining Rig', 'pt-BR': 'Plataforma de Mineração Pesada' },
        description: {
          en: 'A larger extractor with faster ore processing. Mines quicker than a basic rig while drawing less power relative to output.',
          'pt-BR':
            'Um extrator maior com processamento de minério mais rápido. Minera mais rápido que uma plataforma básica consumindo menos energia relativa à produção.',
        },
      },
      {
        rarity: 'EPIC',
        mass: 5,
        structureCost: 7,
        basePrice: 1600,
        scrapValue: 400,
        partHp: 44,
        min: 2.5,
        energyCont: -4,
        name: { en: 'Industrial Mining Rig', 'pt-BR': 'Plataforma de Mineração Industrial' },
        description: {
          en: 'A compact industrial extractor that doubles mining output. Lighter and cheaper on structure than lower-tier rigs.',
          'pt-BR':
            'Um extrator industrial compacto que dobra a produção de mineração. Mais leve e mais barato em estrutura que plataformas de tiers inferiores.',
        },
      },
      {
        rarity: 'LEGENDARY',
        mass: 4,
        structureCost: 6,
        basePrice: 3200,
        scrapValue: 800,
        partHp: 56,
        min: 3,
        energyCont: -4,
        name: { en: 'Planet-Cracker Rig', 'pt-BR': 'Plataforma Quebra-Planetas' },
        description: {
          en: 'A legendary mining rig. Its swarm drills strip asteroids bare in record time while barely taxing the ship.',
          'pt-BR':
            'Uma plataforma de mineração lendária. Suas brocas em enxame depenam asteroides em tempo recorde quase sem taxar a nave.',
        },
      },
    ],
  },
  {
    base: 'mining_rig_heavy',
    partClass: 'UTILITY',
    w: 2,
    h: 2,
    name: { en: 'Deep-Core Mining Rig', 'pt-BR': 'Plataforma de Mineração de Núcleo Profundo' },
    description: {
      en: 'A 2×2 mining rig: far better yields than the standard rig, with the mass and power to match.',
      'pt-BR':
        'Uma plataforma de mineração 2×2: rendimento muito melhor que a padrão, com a massa e a energia correspondentes.',
    },
    tiers: [
      {
        rarity: 'COMMON',
        mass: 19.6,
        structureCost: 23,
        basePrice: 460,
        scrapValue: 115,
        partHp: 33,
        min: 2.3,
        energyCont: -12,
      },
      {
        rarity: 'UNCOMMON',
        mass: 14.7,
        structureCost: 18,
        basePrice: 920,
        scrapValue: 230,
        partHp: 45,
        min: 3.4,
        energyCont: -12,
      },
      {
        rarity: 'RARE',
        mass: 11,
        structureCost: 15,
        basePrice: 1850,
        scrapValue: 462,
        partHp: 61,
        min: 4.6,
        energyCont: -12,
      },
      {
        rarity: 'EPIC',
        mass: 9.2,
        structureCost: 13,
        basePrice: 3700,
        scrapValue: 925,
        partHp: 79,
        min: 5.8,
        energyCont: -8,
      },
      {
        rarity: 'LEGENDARY',
        mass: 7.4,
        structureCost: 11,
        basePrice: 7350,
        scrapValue: 1838,
        partHp: 101,
        min: 6.9,
        energyCont: -8,
      },
    ],
  },
];

export const PARTS: SeedPart[] = FAMILIES.flatMap(rowsOf);

export async function seedParts(prisma: PrismaClient): Promise<void> {
  // One read for what exists, one batched insert for what is missing: the catalog is a few hundred
  // rows and every test world seeds it. Like every other seeded value the rows only FILL what is
  // missing — an admin-edited row (connectorRules included) is never overwritten (DB wins).
  const existing = new Set(
    (await prisma.partCatalog.findMany({ select: { partType: true } })).map((row) => row.partType),
  );
  const missing = PARTS.filter((part) => !existing.has(part.partType));
  const rulesOf = (part: SeedPart) =>
    // Factory default generation rules (connector ports spec): every side central, ENGINE/WEAPON
    // none on the facing side W.
    defaultConnectorRules(part.partClass) as unknown as Prisma.InputJsonValue;
  if (missing.length > 0) {
    await prisma.partCatalog.createMany({
      data: missing.map((part) => ({ ...part, connectorRules: rulesOf(part) })),
    });
  }
  for (const part of PARTS) {
    if (!existing.has(part.partType)) continue;
    await prisma.partCatalog.updateMany({
      where: { partType: part.partType, connectorRules: { equals: Prisma.DbNull } },
      data: { connectorRules: rulesOf(part) },
    });
  }
}
