import type { PartClass, PrismaClient, Rarity } from '@prisma/client';

// Part stats reconciled from the simulators (D10). The simulator values win over
// design/catalogo-pecas-v0.1.md where they conflict.
type SeedPart = {
  partType: string;
  displayName: { en: string; 'pt-BR': string };
  description: { en: string; 'pt-BR': string };
  partClass: PartClass;
  rarity: Rarity;
  w: number;
  h: number;
  mass: number;
  structureCost: number;
  basePrice: number;
  scrapValue: number;
  partHp: number;
  pot?: number;
  pdf?: number;
  bli?: number;
  esc?: number;
  sen?: number;
  crg?: number;
  min?: number;
  energyCont?: number;
  energyCombat?: number;
  fuelCap?: number;
  fuelUse?: number;
  batCharge?: number;
  batOutput?: number;
  batInput?: number;
  /** Flags read by mission requirements: `pressurized` (passenger space), `lifeSupport`. */
  specialProp?: { pressurized?: boolean; lifeSupport?: boolean };
};

export const PARTS: SeedPart[] = [
  {
    partType: 'bridge',
    displayName: { en: 'Bridge', 'pt-BR': 'Ponte de Comando' },
    description: {
      en: 'The command core of your ship. Every ship needs exactly one. It keeps the pilot alive if the rest of the ship is lost, and it sets how much structure (total build weight) the ship can carry.',
      'pt-BR':
        'O núcleo de comando da sua nave. Toda nave precisa de exatamente uma. Ela mantém o piloto vivo se o resto da nave for perdido e define quanta estrutura (peso total de construção) a nave aguenta.',
    },
    partClass: 'BRIDGE',
    rarity: 'COMMON',
    w: 1,
    h: 1,
    mass: 4,
    // Owner: "the bridge could be smaller in structure (like 60 instead of 100)" — the
    // structure budget every ship gets to spend on everything else.
    structureCost: -60,
    basePrice: 0,
    scrapValue: 0,
    partHp: 30,
    energyCont: -1,
  },
  {
    partType: 'bridge_uncommon',
    displayName: { en: 'Command Bridge II', 'pt-BR': 'Ponte de Comando II' },
    description: {
      en: 'An improved command core with a larger structure budget and tougher casing. Better avionics fit in the same compact frame.',
      'pt-BR':
        'Um núcleo de comando aprimorado com maior orçamento de estrutura e casco mais resistente. Aviônicos melhores cabem no mesmo quadro compacto.',
    },
    partClass: 'BRIDGE',
    rarity: 'UNCOMMON',
    w: 1,
    h: 1,
    mass: 4,
    structureCost: -75,
    basePrice: 600,
    scrapValue: 150,
    partHp: 38,
    energyCont: -1,
  },
  {
    partType: 'bridge_rare',
    displayName: { en: 'Command Bridge III', 'pt-BR': 'Ponte de Comando III' },
    description: {
      en: 'A hardened command core for ambitious ships. Offers a much larger structure budget without growing heavier or hungrier.',
      'pt-BR':
        'Um núcleo de comando endurecido para naves ambiciosas. Oferece orçamento de estrutura bem maior sem ficar mais pesado ou faminto.',
    },
    partClass: 'BRIDGE',
    rarity: 'RARE',
    w: 1,
    h: 1,
    mass: 3,
    structureCost: -95,
    basePrice: 1200,
    scrapValue: 300,
    partHp: 48,
    energyCont: -1,
  },
  {
    partType: 'bridge_epic',
    displayName: { en: 'Command Bridge IV', 'pt-BR': 'Ponte de Comando IV' },
    description: {
      en: 'A capital-grade command core. The structure budget is doubled compared to a basic bridge, yet the frame stays compact.',
      'pt-BR':
        'Um núcleo de comando de classe capital. O orçamento de estrutura é o dobro de uma ponte básica, mas o quadro permanece compacto.',
    },
    partClass: 'BRIDGE',
    rarity: 'EPIC',
    w: 1,
    h: 1,
    mass: 3,
    structureCost: -120,
    basePrice: 2400,
    scrapValue: 600,
    partHp: 60,
    energyCont: -1,
  },
  {
    partType: 'bridge_legendary',
    displayName: { en: 'Apex Command Core', 'pt-BR': 'Núcleo de Comando Apex' },
    description: {
      en: 'A near-mythical command core. Its compact shell houses enough structure budget for a small fleet, and the pilot capsule can survive almost anything.',
      'pt-BR':
        'Um núcleo de comando quase mítico. Sua carcaça compacta abriga orçamento de estrutura suficiente para uma pequena frota, e a cápsula do piloto sobrevive a quase tudo.',
    },
    partClass: 'BRIDGE',
    rarity: 'LEGENDARY',
    w: 1,
    h: 1,
    mass: 2,
    structureCost: -150,
    basePrice: 4800,
    scrapValue: 1200,
    partHp: 75,
    energyCont: -1,
  },
  {
    partType: 'engine_chem_small',
    displayName: { en: 'Small Chemical Engine', 'pt-BR': 'Motor Químico Pequeno' },
    description: {
      en: 'A light rocket engine that moves the ship. It burns fuel, so you also need a fuel tank. Cheap and thrifty, but too weak to push a heavy ship fast.',
      'pt-BR':
        'Um motor a foguete leve que move a nave. Ele queima combustível, então você também precisa de um tanque. Barato e econômico, mas fraco demais para mover uma nave pesada rápido.',
    },
    partClass: 'ENGINE',
    rarity: 'COMMON',
    w: 1,
    h: 1,
    mass: 3,
    structureCost: 6,
    basePrice: 100,
    scrapValue: 25,
    partHp: 20,
    pot: 25,
    energyCont: 2,
    fuelUse: 7,
  },
  {
    partType: 'engine_chem_medium',
    displayName: { en: 'Medium Chemical Engine', 'pt-BR': 'Motor Químico Médio' },
    description: {
      en: 'The all-round engine: clearly more thrust than the small one, for more fuel use and mass. A good fit for ships that carry cargo or armor. Needs a fuel tank.',
      'pt-BR':
        'O motor versátil: bem mais empuxo que o pequeno, com mais consumo e massa. Serve bem para naves com carga ou blindagem. Precisa de um tanque de combustível.',
    },
    partClass: 'ENGINE',
    rarity: 'COMMON',
    w: 1,
    h: 2,
    mass: 6,
    structureCost: 10,
    basePrice: 300,
    scrapValue: 75,
    partHp: 30,
    pot: 40,
    energyCont: 4,
    fuelUse: 12,
  },
  {
    partType: 'engine_chem_large',
    displayName: { en: 'Large Chemical Engine', 'pt-BR': 'Motor Químico Grande' },
    description: {
      en: 'Big thrust for big ships. Moves heavy cargo or warship builds at a decent speed, but it is heavy, takes a 2×2 block and burns fuel fast. Needs a fuel tank.',
      'pt-BR':
        'Muito empuxo para naves grandes. Move construções pesadas de carga ou guerra numa velocidade decente, mas é pesado, ocupa um bloco 2×2 e queima combustível rápido. Precisa de um tanque de combustível.',
    },
    partClass: 'ENGINE',
    rarity: 'UNCOMMON',
    w: 2,
    h: 2,
    mass: 14,
    structureCost: 20,
    basePrice: 800,
    scrapValue: 200,
    partHp: 45,
    pot: 70,
    energyCont: 7,
    fuelUse: 25,
  },
  {
    partType: 'engine_ion_micro',
    displayName: { en: 'Micro Ion Engine', 'pt-BR': 'Motor Iônico Micro' },
    description: {
      en: 'A tiny electric drive that burns no fuel, so no tank is needed. Its thrust is low: good for light ships and long trips where refuelling is a hassle. Needs steady power from a reactor or solar panel.',
      'pt-BR':
        'Um pequeno motor elétrico que não queima combustível, então não precisa de tanque. O empuxo é baixo: bom para naves leves e viagens longas em que reabastecer é um problema. Precisa de energia constante de um reator ou painel solar.',
    },
    partClass: 'ENGINE',
    rarity: 'COMMON',
    w: 1,
    h: 1,
    mass: 2,
    structureCost: 5,
    basePrice: 150,
    scrapValue: 38,
    partHp: 15,
    pot: 18,
    energyCont: 0,
    fuelUse: 0,
  },
  {
    partType: 'tank_small',
    displayName: { en: 'Small Fuel Tank', 'pt-BR': 'Tanque de Combustível Pequeno' },
    description: {
      en: 'Holds your fuel. Every chemical engine burns fuel, so a ship with one needs at least one tank; more tanks mean more range between refuels. Adds mass and uses structure.',
      'pt-BR':
        'Guarda o seu combustível. Todo motor químico queima combustível, então uma nave com um precisa de pelo menos um tanque; mais tanques significam mais alcance entre reabastecimentos. Adiciona massa e usa estrutura.',
    },
    partClass: 'TANK',
    rarity: 'COMMON',
    w: 1,
    h: 1,
    mass: 6,
    structureCost: 4,
    basePrice: 400,
    scrapValue: 100,
    partHp: 25,
    fuelCap: 1000,
  },
  {
    partType: 'tank_small_uncommon',
    displayName: { en: 'Medium Fuel Tank', 'pt-BR': 'Tanque de Combustível Médio' },
    description: {
      en: 'A reinforced fuel tank with more capacity than the small model. Lighter materials and better sealing extend range without costing more structure.',
      'pt-BR':
        'Um tanque de combustível reforçado com mais capacidade que o modelo pequeno. Materiais mais leves e melhor vedação estendem o alcance sem custar mais estrutura.',
    },
    partClass: 'TANK',
    rarity: 'UNCOMMON',
    w: 1,
    h: 1,
    mass: 5,
    structureCost: 4,
    basePrice: 800,
    scrapValue: 200,
    partHp: 35,
    fuelCap: 1250,
  },
  {
    partType: 'tank_small_rare',
    displayName: { en: 'Large Fuel Tank', 'pt-BR': 'Tanque de Combustível Grande' },
    description: {
      en: 'A high-capacity fuel tank for long hauls. Advanced alloys make it lighter than lower-tier tanks while holding considerably more fuel.',
      'pt-BR':
        'Um tanque de combustível de alta capacidade para viagens longas. Ligas avançadas o tornam mais leve que tanques de tiers inferiores enquanto guarda bem mais combustível.',
    },
    partClass: 'TANK',
    rarity: 'RARE',
    w: 1,
    h: 1,
    mass: 4,
    structureCost: 4,
    basePrice: 1600,
    scrapValue: 400,
    partHp: 45,
    fuelCap: 1500,
  },
  {
    partType: 'tank_small_epic',
    displayName: { en: 'Extended Fuel Tank', 'pt-BR': 'Tanque de Combustível Estendido' },
    description: {
      en: 'A massive fuel reserve for expedition ships. Holds twice as much as a basic tank while weighing half as much.',
      'pt-BR':
        'Uma reserva massiva de combustível para naves de expedição. Guarda o dobro de um tanque básico pesando metade.',
    },
    partClass: 'TANK',
    rarity: 'EPIC',
    w: 1,
    h: 1,
    mass: 3,
    structureCost: 4,
    basePrice: 3200,
    scrapValue: 800,
    partHp: 55,
    fuelCap: 2000,
  },
  {
    partType: 'tank_small_legendary',
    displayName: { en: 'Capacitance Fuel Cell', 'pt-BR': 'Célula de Combustível de Capacitância' },
    description: {
      en: 'A near-mythical fuel storage unit. Compressed-core technology packs an enormous fuel reserve into a tiny, hardened frame.',
      'pt-BR':
        'Uma unidade de armazenamento de combustível quase mítica. Tecnologia de núcleo comprimido empacota uma reserva enorme em um minúsculo casco endurecido.',
    },
    partClass: 'TANK',
    rarity: 'LEGENDARY',
    w: 1,
    h: 1,
    mass: 3,
    structureCost: 4,
    basePrice: 8000,
    scrapValue: 2000,
    partHp: 65,
    fuelCap: 2500,
  },
  {
    partType: 'battery_small',
    displayName: { en: 'Small Battery', 'pt-BR': 'Bateria Pequena' },
    description: {
      en: 'Stores energy for combat. Shields and lasers draw from it during a fight, and if it cannot cover their demand the ship is not allowed to fly. Small and cheap.',
      'pt-BR':
        'Guarda energia para o combate. Escudos e lasers consomem dela durante a luta, e se ela não cobre a demanda a nave não pode voar. Pequena e barata.',
    },
    partClass: 'BATTERY',
    rarity: 'COMMON',
    w: 1,
    h: 1,
    mass: 5,
    structureCost: 6,
    basePrice: 150,
    scrapValue: 38,
    partHp: 20,
    batCharge: 300,
    batOutput: 80,
  },
  {
    partType: 'battery_small_uncommon',
    displayName: { en: 'Medium Battery', 'pt-BR': 'Bateria Média' },
    description: {
      en: 'A more efficient combat energy store. Fits in the same 1×1 slot as a small battery but holds more charge and output while costing less structure.',
      'pt-BR':
        'Um armazenamento de energia de combate mais eficiente. Cabe no mesmo espaço 1×1 de uma bateria pequena, mas guarda mais carga e saída custando menos estrutura.',
    },
    partClass: 'BATTERY',
    rarity: 'UNCOMMON',
    w: 1,
    h: 1,
    mass: 4,
    structureCost: 5,
    basePrice: 250,
    scrapValue: 63,
    partHp: 28,
    batCharge: 400,
    batOutput: 100,
  },
  {
    partType: 'battery_small_rare',
    displayName: { en: 'High-Density Battery', 'pt-BR': 'Bateria de Alta Densidade' },
    description: {
      en: 'Advanced cell packing doubles the charge density of a basic small battery. Lighter and cheaper on structure than lower-tier models.',
      'pt-BR':
        'Empacotamento avançado de células dobra a densidade de carga de uma bateria pequena básica. Mais leve e mais barata em estrutura que modelos de tiers inferiores.',
    },
    partClass: 'BATTERY',
    rarity: 'RARE',
    w: 1,
    h: 1,
    mass: 3,
    structureCost: 4,
    basePrice: 400,
    scrapValue: 100,
    partHp: 36,
    batCharge: 500,
    batOutput: 130,
  },
  {
    partType: 'battery_small_epic',
    displayName: { en: 'Compact Capacitor Bank', 'pt-BR': 'Banco de Capacitores Compacto' },
    description: {
      en: 'A tiny capacitor bank that holds twice the charge of a basic small battery. Fits in a featherweight frame and costs little structure.',
      'pt-BR':
        'Um minúsculo banco de capacitores que guarda o dobro da carga de uma bateria pequena básica. Cabe num quadro ultraleve e custa pouca estrutura.',
    },
    partClass: 'BATTERY',
    rarity: 'EPIC',
    w: 1,
    h: 1,
    mass: 2,
    structureCost: 3,
    basePrice: 700,
    scrapValue: 175,
    partHp: 44,
    batCharge: 600,
    batOutput: 160,
  },
  {
    partType: 'battery_small_legendary',
    displayName: { en: 'Fusion Cell', 'pt-BR': 'Célula de Fusão' },
    description: {
      en: 'A near-mythical power cell. Its 1×1 shell outperforms most large batteries and costs almost nothing in structure or mass.',
      'pt-BR':
        'Uma célula de energia quase mítica. Sua carcaça 1×1 supera a maioria das baterias grandes e custa quase nada em estrutura ou massa.',
    },
    partClass: 'BATTERY',
    rarity: 'LEGENDARY',
    w: 1,
    h: 1,
    mass: 2,
    structureCost: 2,
    basePrice: 1200,
    scrapValue: 300,
    partHp: 52,
    batCharge: 750,
    batOutput: 200,
  },
  {
    partType: 'battery_large',
    displayName: { en: 'Large Battery', 'pt-BR': 'Bateria Grande' },
    description: {
      en: 'A large energy store for power-hungry builds (lasers plus a shield). Far more charge and output than the small battery, but heavy and a 1×2 block.',
      'pt-BR':
        'Um grande estoque de energia para construções famintas por energia (lasers mais escudo). Muito mais carga e saída que a bateria pequena, mas pesada e ocupa um bloco 1×2.',
    },
    partClass: 'BATTERY',
    rarity: 'UNCOMMON',
    w: 1,
    h: 2,
    mass: 14,
    structureCost: 14,
    basePrice: 400,
    scrapValue: 100,
    partHp: 35,
    batCharge: 900,
    batOutput: 200,
    batInput: 10,
  },
  {
    partType: 'battery_large_rare',
    displayName: { en: 'Heavy Battery Bank', 'pt-BR': 'Banco de Baterias Pesado' },
    description: {
      en: 'A reinforced large battery with denser cells. Holds more charge and recharges faster while shaving off mass and structure cost.',
      'pt-BR':
        'Uma bateria grande reforçada com células mais densas. Guarda mais carga e recarrega mais rápido enquanto reduz massa e custo de estrutura.',
    },
    partClass: 'BATTERY',
    rarity: 'RARE',
    w: 1,
    h: 2,
    mass: 12,
    structureCost: 12,
    basePrice: 700,
    scrapValue: 175,
    partHp: 44,
    batCharge: 1150,
    batOutput: 250,
    batInput: 13,
  },
  {
    partType: 'battery_large_epic',
    displayName: { en: 'Industrial Capacitor Bank', 'pt-BR': 'Banco de Capacitores Industrial' },
    description: {
      en: 'A high-end large battery for capital-grade energy weapons and shields. Doubles the charge of a basic large battery with a lighter frame.',
      'pt-BR':
        'Uma bateria grande de alta qualidade para armas de energia e escudos de classe capital. Dobra a carga de uma bateria grande básica com um quadro mais leve.',
    },
    partClass: 'BATTERY',
    rarity: 'EPIC',
    w: 1,
    h: 2,
    mass: 10,
    structureCost: 10,
    basePrice: 1200,
    scrapValue: 300,
    partHp: 56,
    batCharge: 1450,
    batOutput: 320,
    batInput: 16,
  },
  {
    partType: 'battery_large_legendary',
    displayName: { en: 'Abyssal Core Battery', 'pt-BR': 'Bateria de Núcleo Abissal' },
    description: {
      en: 'A legendary energy reservoir. Its 1×2 frame holds enough charge to power a warship, yet it weighs and costs structure like a mid-tier part.',
      'pt-BR':
        'Um reservatório de energia lendário. Seu quadro 1×2 guarda carga suficiente para alimentar uma nave de guerra, mas pesa e custa estrutura como uma peça de tier médio.',
    },
    partClass: 'BATTERY',
    rarity: 'LEGENDARY',
    w: 1,
    h: 2,
    mass: 8,
    structureCost: 8,
    basePrice: 2000,
    scrapValue: 500,
    partHp: 70,
    batCharge: 1800,
    batOutput: 400,
    batInput: 20,
  },
  {
    partType: 'weapon_ballistic',
    displayName: { en: 'Cannon', 'pt-BR': 'Canhão' },
    description: {
      en: 'A basic cannon. Cheap, reliable damage that needs no energy: a good first weapon for escort missions. Modest firepower.',
      'pt-BR':
        'Um canhão básico. Dano barato e confiável que não usa energia: uma boa primeira arma para missões de escolta. Poder de fogo modesto.',
    },
    partClass: 'WEAPON',
    rarity: 'COMMON',
    w: 1,
    h: 1,
    mass: 3,
    structureCost: 5,
    basePrice: 120,
    scrapValue: 30,
    partHp: 20,
    pdf: 3,
  },
  {
    partType: 'weapon_laser',
    displayName: { en: 'Laser', 'pt-BR': 'Laser' },
    description: {
      en: 'A precise energy weapon with more firepower than the cannon. It draws combat energy from your batteries every round, so pair it with a battery.',
      'pt-BR':
        'Uma arma de energia precisa, com mais poder de fogo que o canhão. Consome energia de combate das baterias a cada rodada, então use com uma bateria.',
    },
    partClass: 'WEAPON',
    rarity: 'UNCOMMON',
    w: 1,
    h: 1,
    mass: 4,
    structureCost: 7,
    basePrice: 350,
    scrapValue: 88,
    partHp: 22,
    pdf: 4,
    energyCombat: -5,
  },
  {
    partType: 'weapon_missile',
    displayName: { en: 'Heavy Missile', 'pt-BR': 'Míssil Pesado' },
    description: {
      en: 'Heavy missiles: the highest firepower of any weapon, paid for in size (1×2), mass and price. Rare. Take it when you expect to fight.',
      'pt-BR':
        'Mísseis pesados: o maior poder de fogo entre as armas, pago em tamanho (1×2), massa e preço. Rara. Leve quando espera lutar.',
    },
    partClass: 'WEAPON',
    rarity: 'RARE',
    w: 1,
    h: 2,
    mass: 6,
    structureCost: 9,
    basePrice: 450,
    scrapValue: 113,
    partHp: 25,
    pdf: 8,
  },
  {
    partType: 'armor_plate',
    displayName: { en: 'Armor Plate', 'pt-BR': 'Placa de Armadura' },
    description: {
      en: 'Heavy armor plating: the most protection per part, cutting the damage from every hit. Very heavy, so it slows your ship down.',
      'pt-BR':
        'Placa de blindagem pesada: a maior proteção por peça, reduzindo o dano de cada ataque. Muito pesada, então deixa a nave mais lenta.',
    },
    partClass: 'DEFENSE',
    rarity: 'UNCOMMON',
    w: 2,
    h: 1,
    mass: 10,
    structureCost: 12,
    basePrice: 500,
    scrapValue: 125,
    partHp: 40,
    bli: 4,
  },
  {
    partType: 'hull',
    displayName: { en: 'Hull Frame', 'pt-BR': 'Estrutura de Casco' },
    description: {
      en: 'A cheap, light structural frame with a little armor. Adds hit points and a touch of protection, but no speed, cargo or firepower.',
      'pt-BR':
        'Uma estrutura barata e leve com um pouco de blindagem. Adiciona pontos de casco e um toque de proteção, mas nenhuma velocidade, carga ou poder de fogo.',
    },
    partClass: 'DEFENSE',
    rarity: 'COMMON',
    w: 2,
    h: 1,
    mass: 4,
    structureCost: 5,
    basePrice: 100,
    scrapValue: 25,
    partHp: 20,
    bli: 1,
  },
  {
    partType: 'hull_uncommon',
    displayName: { en: 'Reinforced Hull Frame', 'pt-BR': 'Estrutura de Casco Reforçada' },
    description: {
      en: 'A stronger structural frame with better plating. Adds more hit points and armor than a basic hull without growing heavier.',
      'pt-BR':
        'Uma estrutura mais forte com melhor blindagem. Adiciona mais pontos de casco e armadura que um casco básico sem ficar mais pesada.',
    },
    partClass: 'DEFENSE',
    rarity: 'UNCOMMON',
    w: 2,
    h: 1,
    mass: 4,
    structureCost: 4,
    basePrice: 200,
    scrapValue: 50,
    partHp: 26,
    bli: 2,
  },
  {
    partType: 'hull_rare',
    displayName: { en: 'Composite Hull Frame', 'pt-BR': 'Estrutura de Casco Composta' },
    description: {
      en: 'An advanced composite frame that is lighter and tougher than standard hull plating. Offers solid protection for mid-tier ships.',
      'pt-BR':
        'Uma estrutura composta avançada mais leve e resistente que o revestimento padrão de casco. Oferece proteção sólida para naves de tier médio.',
    },
    partClass: 'DEFENSE',
    rarity: 'RARE',
    w: 2,
    h: 1,
    mass: 3,
    structureCost: 4,
    basePrice: 400,
    scrapValue: 100,
    partHp: 34,
    bli: 3,
  },
  {
    partType: 'hull_epic',
    displayName: { en: 'Titanium Hull Frame', 'pt-BR': 'Estrutura de Casco de Titânio' },
    description: {
      en: 'A heavy-duty hull frame with military-grade plating. Doubles the protection of a basic hull while costing less structure.',
      'pt-BR':
        'Uma estrutura de casco pesada com blindagem de grau militar. Dobra a proteção de um casco básico custando menos estrutura.',
    },
    partClass: 'DEFENSE',
    rarity: 'EPIC',
    w: 2,
    h: 1,
    mass: 3,
    structureCost: 3,
    basePrice: 800,
    scrapValue: 200,
    partHp: 40,
    bli: 4,
  },
  {
    partType: 'hull_legendary',
    displayName: { en: 'Aegis Hull Frame', 'pt-BR': 'Estrutura de Casco Aegis' },
    description: {
      en: 'A legendary hull frame. Its woven alloy shell shrugs off hits that would shred a normal ship, yet it is remarkably light.',
      'pt-BR':
        'Uma estrutura de casco lendária. Sua casca de liga tecida ignora golpes que destruiriam uma nave normal, mas é notavelmente leve.',
    },
    partClass: 'DEFENSE',
    rarity: 'LEGENDARY',
    w: 2,
    h: 1,
    mass: 2,
    structureCost: 3,
    basePrice: 1600,
    scrapValue: 400,
    partHp: 50,
    bli: 5,
  },
  {
    partType: 'shield_basic',
    displayName: { en: 'Basic Shield', 'pt-BR': 'Escudo Básico' },
    description: {
      en: 'An energy shield: absorbs damage first and recharges between rounds of a fight. Draws combat energy, so it needs a battery. Great against pirates; useless if the battery cannot power it.',
      'pt-BR':
        'Um escudo de energia: absorve o dano primeiro e recarrega entre as rodadas da luta. Consome energia de combate, então precisa de bateria. Ótimo contra piratas; inútil se a bateria não conseguir alimentá-lo.',
    },
    partClass: 'DEFENSE',
    rarity: 'UNCOMMON',
    w: 1,
    h: 1,
    mass: 4,
    structureCost: 7,
    basePrice: 400,
    scrapValue: 100,
    partHp: 25,
    esc: 14,
    energyCombat: -6,
  },
  {
    partType: 'sensor_radar',
    displayName: { en: 'Radar', 'pt-BR': 'Radar' },
    description: {
      en: 'Long-range sensors that spot ambushes before they happen, lowering the chance of being caught by pirates. Draws a little power all the time.',
      'pt-BR':
        'Sensores de longo alcance que detectam emboscadas antes que aconteçam, reduzindo a chance de ser pego por piratas. Consome um pouco de energia o tempo todo.',
    },
    partClass: 'SENSOR',
    rarity: 'COMMON',
    w: 1,
    h: 1,
    mass: 2,
    structureCost: 4,
    basePrice: 200,
    scrapValue: 50,
    partHp: 15,
    sen: 4,
    energyCont: -2,
  },
  {
    partType: 'sensor_radar_uncommon',
    displayName: { en: 'Enhanced Radar', 'pt-BR': 'Radar Aprimorado' },
    description: {
      en: 'A tuned sensor array with better range and clearer signatures. Spots ambushes more reliably than a basic radar.',
      'pt-BR':
        'Uma matriz de sensores sintonizada com maior alcance e assinaturas mais claras. Detecta emboscadas com mais confiança que um radar básico.',
    },
    partClass: 'SENSOR',
    rarity: 'UNCOMMON',
    w: 1,
    h: 1,
    mass: 2,
    structureCost: 3,
    basePrice: 350,
    scrapValue: 88,
    partHp: 20,
    sen: 6,
    energyCont: -2,
  },
  {
    partType: 'sensor_radar_rare',
    displayName: { en: 'Long-Range Scanner', 'pt-BR': 'Scanner de Longo Alcance' },
    description: {
      en: 'A lightweight scanner with extended detection range. Uses less power and structure than lower-tier sensors.',
      'pt-BR':
        'Um scanner leve com alcance de detecção estendido. Usa menos energia e estrutura que sensores de tiers inferiores.',
    },
    partClass: 'SENSOR',
    rarity: 'RARE',
    w: 1,
    h: 1,
    mass: 1,
    structureCost: 3,
    basePrice: 600,
    scrapValue: 150,
    partHp: 26,
    sen: 8,
    energyCont: -1,
  },
  {
    partType: 'sensor_radar_epic',
    displayName: { en: 'Wide-Band Sensor Array', 'pt-BR': 'Matriz de Sensores de Banda Larga' },
    description: {
      en: 'A multi-spectrum array that triples the detection power of a basic radar. Almost no pirate ambush escapes its notice.',
      'pt-BR':
        'Uma matriz multiespectro que triplica o poder de detecção de um radar básico. Quase nenhuma emboscada pirata escapa ao seu alcance.',
    },
    partClass: 'SENSOR',
    rarity: 'EPIC',
    w: 1,
    h: 1,
    mass: 1,
    structureCost: 2,
    basePrice: 1000,
    scrapValue: 250,
    partHp: 30,
    sen: 12,
    energyCont: -1,
  },
  {
    partType: 'sensor_radar_legendary',
    displayName: { en: 'Omniscience Suite', 'pt-BR': 'Suíte de Onisciência' },
    description: {
      en: 'A legendary sensor suite. Its predictive algorithms spot threats before they even form, making ambushes nearly impossible.',
      'pt-BR':
        'Uma suíte de sensores lendária. Seus algoritmos preditivos detectam ameaças antes mesmo de se formarem, tornando emboscadas quase impossíveis.',
    },
    partClass: 'SENSOR',
    rarity: 'LEGENDARY',
    w: 1,
    h: 1,
    mass: 1,
    structureCost: 2,
    basePrice: 1600,
    scrapValue: 400,
    partHp: 38,
    sen: 16,
    energyCont: -1,
  },
  {
    partType: 'cargo',
    displayName: { en: 'Cargo Hold', 'pt-BR': 'Compartimento de Carga' },
    description: {
      en: 'Cargo space. Each hold adds capacity for deliveries, so more holds mean bigger, better-paid jobs. Adds mass, which slows the ship.',
      'pt-BR':
        'Espaço de carga. Cada compartimento aumenta a capacidade para entregas, então mais compartimentos significam trabalhos maiores e mais bem pagos. Adiciona massa, o que deixa a nave mais lenta.',
    },
    partClass: 'CARGO',
    rarity: 'COMMON',
    w: 1,
    h: 1,
    mass: 2,
    structureCost: 4,
    basePrice: 80,
    scrapValue: 20,
    partHp: 15,
    crg: 5,
  },
  {
    partType: 'cargo_uncommon',
    displayName: { en: 'Reinforced Cargo Hold', 'pt-BR': 'Compartimento de Carga Reforçado' },
    description: {
      en: 'A sturdier cargo hold with slightly more capacity. Uses the same 1×1 space as a basic hold but costs less structure.',
      'pt-BR':
        'Um compartimento de carga mais resistente com um pouco mais de capacidade. Usa o mesmo espaço 1×1 de um compartimento básico, mas custa menos estrutura.',
    },
    partClass: 'CARGO',
    rarity: 'UNCOMMON',
    w: 1,
    h: 1,
    mass: 2,
    structureCost: 3,
    basePrice: 150,
    scrapValue: 38,
    partHp: 20,
    crg: 6,
  },
  {
    partType: 'cargo_rare',
    displayName: { en: 'Expanded Cargo Hold', 'pt-BR': 'Compartimento de Carga Expandido' },
    description: {
      en: 'A lightweight cargo hold with more capacity than the basic model. Advanced materials cut both mass and structure cost.',
      'pt-BR':
        'Um compartimento de carga leve com mais capacidade que o modelo básico. Materiais avançados reduzem massa e custo de estrutura.',
    },
    partClass: 'CARGO',
    rarity: 'RARE',
    w: 1,
    h: 1,
    mass: 1,
    structureCost: 3,
    basePrice: 300,
    scrapValue: 75,
    partHp: 25,
    crg: 8,
  },
  {
    partType: 'cargo_epic',
    displayName: { en: 'High-Capacity Hold', 'pt-BR': 'Compartimento de Alta Capacidade' },
    description: {
      en: 'A compact freight bay that holds twice as much cargo as a basic hold. Fits in a featherweight 1×1 frame.',
      'pt-BR':
        'Um compartimento de carga compacto que guarda o dobro de carga de um compartimento básico. Cabe num minúsculo quadro 1×1.',
    },
    partClass: 'CARGO',
    rarity: 'EPIC',
    w: 1,
    h: 1,
    mass: 1,
    structureCost: 2,
    basePrice: 600,
    scrapValue: 150,
    partHp: 30,
    crg: 10,
  },
  {
    partType: 'cargo_legendary',
    displayName: { en: 'Void-Fold Cargo Bay', 'pt-BR': 'Baía de Carga de Dobra do Vazio' },
    description: {
      en: 'A legendary freight module. Its compressed storage lattice fits a small freighter’s worth of cargo into a single 1×1 slot.',
      'pt-BR':
        'Um módulo de carga lendário. Sua malha de armazenamento comprimido cabe a carga de um pequeno cargueiro num único slot 1×1.',
    },
    partClass: 'CARGO',
    rarity: 'LEGENDARY',
    w: 1,
    h: 1,
    mass: 1,
    structureCost: 2,
    basePrice: 1200,
    scrapValue: 300,
    partHp: 38,
    crg: 13,
  },
  {
    partType: 'passenger_cabin',
    displayName: { en: 'Passenger Cabin', 'pt-BR': 'Cabine de Passageiros' },
    description: {
      en: 'A pressurized cabin for people instead of freight. Transport missions need one, and so do some rescues. It only works together with a Life Support module, and adds mass.',
      'pt-BR':
        'Uma cabine pressurizada para pessoas em vez de carga. Missões de transporte precisam de uma, e alguns resgates também. Só funciona junto com um módulo de Suporte de Vida e adiciona massa.',
    },
    partClass: 'CARGO',
    rarity: 'COMMON',
    w: 1,
    h: 2,
    mass: 6,
    structureCost: 8,
    basePrice: 260,
    scrapValue: 60,
    partHp: 25,
    energyCont: -1,
    specialProp: { pressurized: true },
  },
  {
    partType: 'life_support',
    displayName: { en: 'Life Support', 'pt-BR': 'Suporte de Vida' },
    description: {
      en: 'Air, heat and water for everyone aboard. Any ship with a Passenger Cabin must carry one or it is not allowed to fly. Draws steady power all the time.',
      'pt-BR':
        'Ar, calor e água para todos a bordo. Toda nave com uma Cabine de Passageiros precisa carregar um, senão não pode voar. Consome energia constante o tempo todo.',
    },
    partClass: 'UTILITY',
    rarity: 'COMMON',
    w: 1,
    h: 1,
    mass: 3,
    structureCost: 4,
    basePrice: 300,
    scrapValue: 70,
    partHp: 15,
    energyCont: -3,
    specialProp: { lifeSupport: true },
  },
  {
    partType: 'mining_rig',
    displayName: { en: 'Mining Rig', 'pt-BR': 'Plataforma de Mineração' },
    description: {
      en: 'An automated extractor. Needed for mining missions and for pulling ore out of asteroid fields, which you sell at ports. Draws steady power and adds mass.',
      'pt-BR':
        'Um extrator automático. Necessária para missões de mineração e para tirar minério de campos de asteroides, que você vende nos portos. Consome energia constante e adiciona massa.',
    },
    partClass: 'UTILITY',
    rarity: 'UNCOMMON',
    w: 1,
    h: 2,
    mass: 8,
    structureCost: 10,
    basePrice: 400,
    scrapValue: 100,
    partHp: 25,
    min: 1,
    energyCont: -3,
  },
  {
    partType: 'reactor_solar',
    displayName: { en: 'Solar Panel', 'pt-BR': 'Painel Solar' },
    description: {
      en: 'A light solar array with a small but constant power output. Covers what engines, radar and rigs draw in flight at almost no weight.',
      'pt-BR':
        'Um painel solar leve com produção de energia pequena, mas constante. Cobre o que motores, radar e mineradoras consomem em voo, com quase nenhum peso.',
    },
    partClass: 'REACTOR',
    rarity: 'COMMON',
    w: 1,
    h: 1,
    mass: 2,
    structureCost: 3,
    basePrice: 300,
    scrapValue: 75,
    partHp: 15,
    energyCont: 30,
  },
  {
    partType: 'reactor_nuclear',
    displayName: { en: 'Nuclear Reactor', 'pt-BR': 'Reator Nuclear' },
    description: {
      en: 'A heavy fission reactor with a very large power output, for builds full of power-hungry parts. Rare, expensive and heavy (2×2).',
      'pt-BR':
        'Um reator de fissão pesado com produção de energia muito alta, para construções cheias de peças que consomem muita energia. Raro, caro e pesado (2×2).',
    },
    partClass: 'REACTOR',
    rarity: 'RARE',
    w: 2,
    h: 2,
    mass: 14,
    structureCost: 18,
    basePrice: 2000,
    scrapValue: 500,
    partHp: 40,
    energyCont: 180,
  },
];

export async function seedParts(prisma: PrismaClient): Promise<void> {
  for (const part of PARTS) {
    const existing = await prisma.partCatalog.findUnique({ where: { partType: part.partType } });
    if (existing === null) {
      await prisma.partCatalog.create({ data: part });
    }
  }
}
