import type { PrismaClient, Rarity } from '@prisma/client';

// The assembly yards (ship formats) as the Admin has them today. Each is a set of [x, y] cells the
// ship's parts must fit inside; a bridge of the format's `minRarity` (or better) unlocks it. Like
// every seeded value they only FILL what is missing: a format an admin edited keeps its values.
type SeedShipFormat = {
  id: string;
  displayName: { en: string; 'pt-BR': string };
  description: { en: string; 'pt-BR': string };
  minRarity: Rarity;
  active: boolean;
  /** How many cells the format is meant to have (the Admin's cell editor shows it as the target). */
  cellTarget: number;
  cells: [number, number][];
};

export const SHIP_FORMATS: SeedShipFormat[] = [
  {
    id: 'classic_square',
    displayName: { en: 'Classic Square', 'pt-BR': 'Quadrado Clássico' },
    description: { en: 'The original start pack', 'pt-BR': 'Grade basica 1' },
    minRarity: 'COMMON',
    active: true,
    cellTarget: 26,
    cells: [
      [-4, -1],
      [-4, 0],
      [-4, 1],
      [-3, -2],
      [-3, -1],
      [-3, 0],
      [-3, 1],
      [-3, 2],
      [-2, -2],
      [-2, -1],
      [-2, 0],
      [-2, 1],
      [-2, 2],
      [-1, -2],
      [-1, -1],
      [-1, 0],
      [-1, 1],
      [-1, 2],
      [0, -1],
      [0, 0],
      [0, 1],
      [1, -1],
      [1, 0],
      [1, 1],
      [2, 0],
    ],
  },
  {
    id: 'classic_round',
    displayName: { en: 'Basic initial ship', 'pt-BR': 'Nave basica inicial' },
    description: { en: 'Basic', 'pt-BR': 'Basica' },
    minRarity: 'COMMON',
    active: true,
    cellTarget: 26,
    cells: [
      [-3, 0],
      [-2, -2],
      [-2, -1],
      [-2, 0],
      [-2, 1],
      [-2, 2],
      [-1, -2],
      [-1, -1],
      [-1, 0],
      [-1, 1],
      [-1, 2],
      [0, -2],
      [0, -1],
      [0, 0],
      [0, 1],
      [0, 2],
      [1, -1],
      [1, 0],
      [1, 1],
      [2, -1],
      [2, 0],
      [2, 1],
      [3, -1],
      [3, 0],
      [3, 1],
    ],
  },
  {
    id: 'uncommon_rocket',
    displayName: { en: 'rocket', 'pt-BR': 'foguete' },
    description: { en: 'Rocket format', 'pt-BR': 'formato de foguete' },
    minRarity: 'UNCOMMON',
    active: true,
    cellTarget: 30,
    cells: [
      [-5, -3],
      [-5, 3],
      [-4, -3],
      [-4, -2],
      [-4, 2],
      [-4, 3],
      [-3, -2],
      [-3, -1],
      [-3, 0],
      [-3, 1],
      [-3, 2],
      [-2, -2],
      [-2, -1],
      [-2, 0],
      [-2, 1],
      [-2, 2],
      [-1, -2],
      [-1, -1],
      [-1, 0],
      [-1, 1],
      [-1, 2],
      [0, -1],
      [0, 0],
      [0, 1],
      [1, -1],
      [1, 0],
      [1, 1],
      [2, -1],
      [2, 0],
      [2, 1],
    ],
  },
  {
    id: 'uncommon_rocket_2',
    displayName: { en: 'rocket 2', 'pt-BR': 'foguete 2' },
    description: { en: 'Rocket format', 'pt-BR': 'formato de foguete' },
    minRarity: 'UNCOMMON',
    active: true,
    cellTarget: 30,
    cells: [
      [-4, -3],
      [-4, -2],
      [-4, -1],
      [-4, 0],
      [-4, 1],
      [-4, 2],
      [-4, 3],
      [-3, -2],
      [-3, -1],
      [-3, 0],
      [-3, 1],
      [-3, 2],
      [-2, -2],
      [-2, -1],
      [-2, 0],
      [-2, 1],
      [-2, 2],
      [-1, -2],
      [-1, -1],
      [-1, 0],
      [-1, 1],
      [-1, 2],
      [0, -1],
      [0, 0],
      [0, 1],
      [0, 2],
      [1, -1],
      [1, 0],
      [1, 1],
      [2, 0],
    ],
  },
  {
    id: 'uncommon_rocket_3',
    displayName: { en: 'rocket 3', 'pt-BR': 'foguete 3' },
    description: { en: 'Rocket format', 'pt-BR': 'formato de foguete' },
    minRarity: 'UNCOMMON',
    active: true,
    cellTarget: 30,
    cells: [
      [-5, -2],
      [-5, 2],
      [-4, -3],
      [-4, -2],
      [-4, 2],
      [-4, 3],
      [-3, -3],
      [-3, -2],
      [-3, -1],
      [-3, 0],
      [-3, 1],
      [-3, 2],
      [-3, 3],
      [-2, -2],
      [-2, -1],
      [-2, 0],
      [-2, 1],
      [-2, 2],
      [-1, -2],
      [-1, -1],
      [-1, 0],
      [-1, 1],
      [-1, 2],
      [0, -1],
      [0, 0],
      [0, 1],
      [1, -1],
      [1, 0],
      [1, 1],
      [2, 0],
    ],
  },
  {
    id: 'rare_1',
    displayName: { en: 'modelo raro 1', 'pt-BR': 'modelo raro 1' },
    description: { en: 'Rare model 1', 'pt-BR': 'Modelo raro 1' },
    minRarity: 'RARE',
    active: true,
    cellTarget: 45,
    cells: [
      [-4, -2],
      [-4, -1],
      [-4, 0],
      [-4, 1],
      [-4, 2],
      [-3, -2],
      [-3, -1],
      [-3, 0],
      [-3, 1],
      [-3, 2],
      [-2, -2],
      [-2, -1],
      [-2, 0],
      [-2, 1],
      [-2, 2],
      [-1, -3],
      [-1, -2],
      [-1, -1],
      [-1, 0],
      [-1, 1],
      [-1, 2],
      [-1, 3],
      [0, -3],
      [0, -2],
      [0, -1],
      [0, 0],
      [0, 1],
      [0, 2],
      [0, 3],
      [1, -2],
      [1, -1],
      [1, 0],
      [1, 1],
      [1, 2],
      [2, -2],
      [2, -1],
      [2, 0],
      [2, 1],
      [2, 2],
      [3, -1],
      [3, 0],
      [3, 1],
      [4, -1],
      [4, 0],
      [4, 1],
    ],
  },
  {
    id: 'rare_2_copy',
    displayName: { en: 'modelo raro 2', 'pt-BR': 'modelo raro 2' },
    description: { en: 'Rare model 2', 'pt-BR': 'Modelo raro 2' },
    minRarity: 'RARE',
    active: true,
    cellTarget: 45,
    cells: [
      [-5, -2],
      [-5, -1],
      [-5, 0],
      [-5, 1],
      [-5, 2],
      [-4, -1],
      [-4, 0],
      [-4, 1],
      [-3, -3],
      [-3, -1],
      [-3, 0],
      [-3, 1],
      [-3, 3],
      [-2, -3],
      [-2, -2],
      [-2, -1],
      [-2, 0],
      [-2, 1],
      [-2, 2],
      [-2, 3],
      [-1, -3],
      [-1, -2],
      [-1, -1],
      [-1, 0],
      [-1, 1],
      [-1, 2],
      [-1, 3],
      [0, -2],
      [0, -1],
      [0, 0],
      [0, 1],
      [0, 2],
      [1, -2],
      [1, -1],
      [1, 0],
      [1, 1],
      [1, 2],
      [2, -2],
      [2, -1],
      [2, 0],
      [2, 1],
      [2, 2],
      [3, -1],
      [3, 0],
      [3, 1],
    ],
  },
  {
    id: 'epic_1',
    displayName: { en: 'modelo epic 1', 'pt-BR': 'modelo epic 2' },
    description: { en: 'Epic model 1', 'pt-BR': 'Modelo epico 1' },
    minRarity: 'EPIC',
    active: true,
    cellTarget: 60,
    cells: [
      [-5, -3],
      [-5, -2],
      [-5, -1],
      [-5, 0],
      [-5, 1],
      [-5, 2],
      [-5, 3],
      [-4, -2],
      [-4, -1],
      [-4, 0],
      [-4, 1],
      [-4, 2],
      [-3, -5],
      [-3, -3],
      [-3, -2],
      [-3, -1],
      [-3, 0],
      [-3, 1],
      [-3, 2],
      [-3, 3],
      [-3, 5],
      [-2, -5],
      [-2, -4],
      [-2, -3],
      [-2, -2],
      [-2, -1],
      [-2, 0],
      [-2, 1],
      [-2, 2],
      [-2, 3],
      [-2, 4],
      [-2, 5],
      [-1, -4],
      [-1, -3],
      [-1, -2],
      [-1, -1],
      [-1, 0],
      [-1, 1],
      [-1, 2],
      [-1, 3],
      [-1, 4],
      [0, -3],
      [0, -2],
      [0, -1],
      [0, 0],
      [0, 1],
      [0, 2],
      [0, 3],
      [1, -2],
      [1, -1],
      [1, 0],
      [1, 1],
      [1, 2],
      [2, -1],
      [2, 0],
      [2, 1],
      [3, -1],
      [3, 0],
      [3, 1],
      [4, 0],
    ],
  },
  {
    id: 'epic_2_copy',
    displayName: { en: 'modelo epic 2', 'pt-BR': 'modelo epic 2' },
    description: { en: 'Epic model 2', 'pt-BR': 'Modelo epico 2' },
    minRarity: 'EPIC',
    active: true,
    cellTarget: 60,
    cells: [
      [-6, -2],
      [-6, -1],
      [-6, 1],
      [-6, 2],
      [-5, -2],
      [-5, -1],
      [-5, 0],
      [-5, 1],
      [-5, 2],
      [-4, -3],
      [-4, -2],
      [-4, -1],
      [-4, 0],
      [-4, 1],
      [-4, 2],
      [-4, 3],
      [-3, -3],
      [-3, -2],
      [-3, -1],
      [-3, 0],
      [-3, 1],
      [-3, 2],
      [-3, 3],
      [-2, -3],
      [-2, -2],
      [-2, -1],
      [-2, 0],
      [-2, 1],
      [-2, 2],
      [-2, 3],
      [-1, -3],
      [-1, -2],
      [-1, -1],
      [-1, 0],
      [-1, 1],
      [-1, 2],
      [-1, 3],
      [0, -3],
      [0, -2],
      [0, -1],
      [0, 0],
      [0, 1],
      [0, 2],
      [0, 3],
      [1, -3],
      [1, -2],
      [1, -1],
      [1, 0],
      [1, 1],
      [1, 2],
      [1, 3],
      [2, -2],
      [2, -1],
      [2, 0],
      [2, 1],
      [2, 2],
      [3, -1],
      [3, 0],
      [3, 1],
      [4, 0],
    ],
  },
];

export async function seedShipFormats(prisma: PrismaClient): Promise<void> {
  for (const format of SHIP_FORMATS) {
    const existing = await prisma.shipFormat.findUnique({ where: { id: format.id } });
    if (existing !== null) continue;
    await prisma.shipFormat.create({ data: format });
  }
}
