import type { ConfigKey, ConfigRegistryEntry } from './game-config.types.js';
import { GAME_CONFIG_DEFAULTS } from './game-config.defaults.js';

export const CONFIG_REGISTRY: readonly ConfigRegistryEntry[] = [
  {
    key: 'combat.dodge_factor',
    group: 'combat',
    type: 'number',
    min: 0.1,
    max: 5.0,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.combat.dodge_factor),
    description: {
      en: 'Multiplier applied to dodge rating when evading an attack.',
      'pt-BR': 'Multiplicador aplicado à avaliação de esquiva ao desviar de um ataque.',
    },
  },
  {
    key: 'combat.dc_base',
    group: 'combat',
    type: 'integer',
    min: 1,
    max: 50,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.combat.dc_base),
    description: {
      en: 'Base difficulty class for attack rolls.',
      'pt-BR': 'Classe de dificuldade base para rolagens de ataque.',
    },
  },
  {
    key: 'combat.attack_die',
    group: 'combat',
    type: 'integer',
    min: 2,
    max: 100,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.combat.attack_die),
    description: {
      en: 'Die size used when rolling to hit.',
      'pt-BR': 'Tamanho do dado usado ao rolar para acertar.',
    },
  },
  {
    key: 'combat.damage_die',
    group: 'combat',
    type: 'integer',
    min: 2,
    max: 20,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.combat.damage_die),
    description: {
      en: 'Die size used when rolling damage.',
      'pt-BR': 'Tamanho do dado usado ao rolar dano.',
    },
  },
  {
    key: 'combat.armor_cap',
    group: 'combat',
    type: 'integer',
    min: 0,
    max: 20,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.combat.armor_cap),
    description: {
      en: 'Maximum armor value that can reduce incoming damage.',
      'pt-BR': 'Valor máximo de armadura que pode reduzir dano recebido.',
    },
  },
  {
    key: 'combat.pierce_ratio',
    group: 'combat',
    type: 'number',
    min: 0,
    max: 1,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.combat.pierce_ratio),
    description: {
      en: 'Fraction of damage that ignores armor. Inert in v0.1.',
      'pt-BR': 'Fração do dano que ignora armadura. Inerte na v0.1.',
    },
  },
  {
    key: 'combat.pierce_min_pdf',
    group: 'combat',
    type: 'integer',
    min: 0,
    max: 50,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.combat.pierce_min_pdf),
    description: {
      en: 'Minimum PDF required to trigger piercing damage.',
      'pt-BR': 'PDF mínimo necessário para ativar dano perfurante.',
    },
  },
  {
    key: 'combat.shield_regen',
    group: 'combat',
    type: 'number',
    min: 0,
    max: 20,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.combat.shield_regen),
    description: {
      en: 'Shield regeneration rate per combat round.',
      'pt-BR': 'Taxa de regeneração de escudo por rodada de combate.',
    },
  },
  {
    key: 'combat.kite_factor',
    group: 'combat',
    type: 'number',
    min: 0,
    max: 1,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.combat.kite_factor),
    description: {
      en: 'Effectiveness penalty when kiting away from an enemy.',
      'pt-BR': 'Penalidade de efetividade ao manter distância do inimigo.',
    },
  },
  {
    key: 'combat.first_strike_bonus',
    group: 'combat',
    type: 'integer',
    min: 0,
    max: 10,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.combat.first_strike_bonus),
    description: {
      en: 'Bonus to the first attack roll in a combat exchange.',
      'pt-BR': 'Bônus na primeira rolagem de ataque de uma troca de combate.',
    },
  },
  {
    key: 'combat.max_rounds',
    group: 'combat',
    type: 'integer',
    min: 1,
    max: 200,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.combat.max_rounds),
    description: {
      en: 'Maximum number of combat rounds before a draw is declared.',
      'pt-BR': 'Número máximo de rodadas de combate antes de declarar empate.',
    },
  },
  {
    key: 'combat.retreat_hp_ratio',
    group: 'combat',
    type: 'number',
    min: 0.05,
    max: 0.5,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.combat.retreat_hp_ratio),
    description: {
      en: 'HP ratio at which a ship auto-retreats from combat.',
      'pt-BR': 'Proporção de HP na qual uma nave se retira automaticamente do combate.',
    },
  },
  {
    key: 'ship.mob_factor',
    group: 'ship',
    type: 'number',
    min: 0.1,
    max: 5.0,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.ship.mob_factor),
    description: {
      en: 'Multiplier converting mobility stat into combat advantage.',
      'pt-BR': 'Multiplicador que converte estatística de mobilidade em vantagem de combate.',
    },
  },
  {
    key: 'ship.fuel_mass_per_unit',
    group: 'ship',
    type: 'number',
    min: 0,
    max: 1,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.ship.fuel_mass_per_unit),
    description: {
      en: 'Mass contributed by each unit of fuel carried.',
      'pt-BR': 'Massa adicionada por cada unidade de combustível carregada.',
    },
  },
  {
    key: 'wear.performance_floor',
    group: 'wear',
    type: 'number',
    min: 0,
    max: 1,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.wear.performance_floor),
    description: {
      en: 'Lowest performance multiplier a worn part can reach.',
      'pt-BR': 'Multiplicador de desempenho mínimo que uma peça desgastada pode atingir.',
    },
  },
  {
    key: 'wear.performance_slope',
    group: 'wear',
    type: 'number',
    min: 0,
    max: 2,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.wear.performance_slope),
    description: {
      en: 'How quickly performance drops as condition decreases.',
      'pt-BR': 'Quão rápido o desempenho cai à medida que a condição diminui.',
    },
  },
  {
    key: 'wear.choke_threshold',
    group: 'wear',
    type: 'integer',
    min: 1,
    max: 100,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.wear.choke_threshold),
    description: {
      en: 'Condition threshold below which a part may choke.',
      'pt-BR': 'Limite de condição abaixo do qual uma peça pode falhar.',
    },
  },
  {
    key: 'wear.dead_at_or_below',
    group: 'wear',
    type: 'integer',
    min: 0,
    max: 10,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.wear.dead_at_or_below),
    description: {
      en: 'Condition at or below which a part is considered broken.',
      'pt-BR': 'Condição igual ou abaixo da qual uma peça é considerada quebrada.',
    },
  },
  {
    key: 'wear.base_min',
    group: 'wear',
    type: 'integer',
    min: 0,
    max: 20,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.wear.base_min),
    description: {
      en: 'Minimum base wear loss per applicable event.',
      'pt-BR': 'Perda mínima base de desgaste por evento aplicável.',
    },
  },
  {
    key: 'wear.base_max',
    group: 'wear',
    type: 'integer',
    min: 0,
    max: 20,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.wear.base_max),
    description: {
      en: 'Maximum base wear loss per applicable event.',
      'pt-BR': 'Perda máxima base de desgaste por evento aplicável.',
    },
  },
  {
    key: 'wear.env_multiplier',
    group: 'wear',
    type: 'number',
    min: 0,
    max: 5,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.wear.env_multiplier),
    description: {
      en: 'Multiplier for wear caused by hazardous environments.',
      'pt-BR': 'Multiplicador para desgaste causado por ambientes perigosos.',
    },
  },
  {
    key: 'wear.choke_loss_min',
    group: 'wear',
    type: 'integer',
    min: 0,
    max: 20,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.wear.choke_loss_min),
    description: {
      en: 'Minimum condition loss on a part choke event.',
      'pt-BR': 'Perda mínima de condição em evento de falha de peça.',
    },
  },
  {
    key: 'wear.choke_loss_max',
    group: 'wear',
    type: 'integer',
    min: 0,
    max: 50,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.wear.choke_loss_max),
    description: {
      en: 'Maximum condition loss on a part choke event.',
      'pt-BR': 'Perda máxima de condição em evento de falha de peça.',
    },
  },
  {
    key: 'wear.defeat_loss_min',
    group: 'wear',
    type: 'integer',
    min: 0,
    max: 50,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.wear.defeat_loss_min),
    description: {
      en: 'Minimum condition loss applied to parts on combat defeat.',
      'pt-BR': 'Perda mínima de condição aplicada às peças na derrota em combate.',
    },
  },
  {
    key: 'wear.defeat_loss_max',
    group: 'wear',
    type: 'integer',
    min: 0,
    max: 50,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.wear.defeat_loss_max),
    description: {
      en: 'Maximum condition loss applied to parts on combat defeat.',
      'pt-BR': 'Perda máxima de condição aplicada às peças na derrota em combate.',
    },
  },
  {
    key: 'wear.overload_min',
    group: 'wear',
    type: 'integer',
    min: 0,
    max: 50,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.wear.overload_min),
    description: {
      en: 'Minimum condition loss from overload events.',
      'pt-BR': 'Perda mínima de condição por eventos de sobrecarga.',
    },
  },
  {
    key: 'wear.overload_max',
    group: 'wear',
    type: 'integer',
    min: 0,
    max: 50,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.wear.overload_max),
    description: {
      en: 'Maximum condition loss from overload events.',
      'pt-BR': 'Perda máxima de condição por eventos de sobrecarga.',
    },
  },
  {
    key: 'wear.scale_mode',
    group: 'wear',
    type: 'string',
    min: 0,
    max: 0,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.wear.scale_mode),
    description: {
      en: 'How part condition scales ship stats: all_stats or hp_only.',
      'pt-BR': 'Como a condição da peça escala os atributos da nave: all_stats ou hp_only.',
    },
  },
  {
    key: 'economy.fuel_price',
    group: 'economy',
    type: 'integer',
    min: 1,
    max: 20,
    unit: '¢',
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.economy.fuel_price),
    description: {
      en: 'Price of one unit of fuel.',
      'pt-BR': 'Preço de uma unidade de combustível.',
    },
  },
  {
    key: 'economy.repair_price',
    group: 'economy',
    type: 'integer',
    min: 1,
    max: 20,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.economy.repair_price),
    description: {
      en: 'Base price of one point of hull repair.',
      'pt-BR': 'Preço base de um ponto de reparo do casco.',
    },
  },
  {
    key: 'economy.repair_price_ref',
    group: 'economy',
    type: 'integer',
    min: 1,
    max: 20,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.economy.repair_price_ref),
    description: {
      en: 'Reference repair price used in price formulas.',
      'pt-BR': 'Preço de reparo de referência usado em fórmulas de preço.',
    },
  },
  {
    key: 'economy.repair_factor',
    group: 'economy',
    type: 'number',
    min: 0.1,
    max: 2.0,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.economy.repair_factor),
    description: {
      en: 'Global multiplier applied to repair costs.',
      'pt-BR': 'Multiplicador global aplicado aos custos de reparo.',
    },
  },
  {
    key: 'economy.maintenance_per_tier',
    group: 'economy',
    type: 'integer',
    min: 0,
    max: 1000,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.economy.maintenance_per_tier),
    description: {
      en: 'Base maintenance cost per ship tier.',
      'pt-BR': 'Custo base de manutenção por tier da nave.',
    },
  },
  {
    key: 'economy.reward_base',
    group: 'economy',
    type: 'integer',
    min: 0,
    max: 10000,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.economy.reward_base),
    description: {
      en: 'Base mission reward before modifiers.',
      'pt-BR': 'Recompensa base de missão antes de modificadores.',
    },
  },
  {
    key: 'economy.reward_per_tier',
    group: 'economy',
    type: 'integer',
    min: 0,
    max: 2000,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.economy.reward_per_tier),
    description: {
      en: 'Extra mission reward per ship tier.',
      'pt-BR': 'Recompensa extra de missão por tier da nave.',
    },
  },
  {
    key: 'economy.reward_danger_divisor',
    group: 'economy',
    type: 'integer',
    min: 1,
    max: 100,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.economy.reward_danger_divisor),
    description: {
      en: 'Divisor controlling how danger affects mission reward.',
      'pt-BR': 'Divisor que controla como o perigo afeta a recompensa da missão.',
    },
  },
  {
    key: 'economy.reward_distance_ref',
    group: 'economy',
    type: 'integer',
    min: 100,
    max: 5000,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.economy.reward_distance_ref),
    description: {
      en: 'Reference distance for reward scaling.',
      'pt-BR': 'Distância de referência para escala de recompensa.',
    },
  },
  {
    key: 'economy.reward_distance_divisor',
    group: 'economy',
    type: 'integer',
    min: 100,
    max: 10000,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.economy.reward_distance_divisor),
    description: {
      en: 'Divisor controlling distance contribution to reward.',
      'pt-BR': 'Divisor que controla a contribuição da distância na recompensa.',
    },
  },
  {
    key: 'economy.reward_type_bonus',
    group: 'economy',
    type: 'json',
    min: 0,
    max: 5,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.economy.reward_type_bonus),
    description: {
      en: 'Multiplier per mission type applied to mission rewards.',
      'pt-BR': 'Multiplicador por tipo de missão aplicado às recompensas.',
    },
  },
  {
    key: 'economy.combat_win_base',
    group: 'economy',
    type: 'integer',
    min: 0,
    max: 1000,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.economy.combat_win_base),
    description: {
      en: 'Base credits awarded for winning a combat encounter.',
      'pt-BR': 'Créditos base concedidos por vencer um encontro de combate.',
    },
  },
  {
    key: 'economy.combat_win_per_tier',
    group: 'economy',
    type: 'integer',
    min: 0,
    max: 500,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.economy.combat_win_per_tier),
    description: {
      en: 'Extra credits per tier awarded for winning combat.',
      'pt-BR': 'Créditos extras por tier concedidos por vencer combate.',
    },
  },
  {
    key: 'economy.combat_loss_penalty',
    group: 'economy',
    type: 'integer',
    min: 0,
    max: 1000,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.economy.combat_loss_penalty),
    description: {
      en: 'Credits deducted after losing a combat encounter.',
      'pt-BR': 'Créditos deduzidos após perder um encontro de combate.',
    },
  },
  {
    key: 'economy.upgrade_costs',
    group: 'economy',
    type: 'json',
    min: 0,
    max: 100000,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.economy.upgrade_costs),
    description: {
      en: 'Tier upgrade cost thresholds.',
      'pt-BR': 'Limites de custo de upgrade por tier.',
    },
  },
  {
    key: 'economy.start_credits',
    group: 'economy',
    type: 'integer',
    min: 0,
    max: 10000,
    unit: '¢',
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.economy.start_credits),
    description: {
      en: 'Starting credits for a new player.',
      'pt-BR': 'Créditos iniciais para um novo jogador.',
    },
  },
  {
    key: 'economy.rescue_cost',
    group: 'economy',
    type: 'integer',
    min: 0,
    max: 10000,
    unit: '¢',
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.economy.rescue_cost),
    description: {
      en: 'Cost to dispatch a rescue mission.',
      'pt-BR': 'Custo para despachar uma missão de resgate.',
    },
  },
  {
    key: 'economy.rescue_fuel_fraction',
    group: 'economy',
    type: 'number',
    min: 0,
    max: 1,
    unit: '×',
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.economy.rescue_fuel_fraction),
    description: {
      en: 'Share of the tank a rescued ship is left with (emergency ration; 0 = empty).',
      'pt-BR': 'Fração do tanque com que a nave resgatada fica (ração de emergência; 0 = vazio).',
    },
  },
  {
    key: 'economy.sell_ratio',
    group: 'economy',
    type: 'number',
    min: 0,
    max: 1,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.economy.sell_ratio),
    description: {
      en: 'Fraction of base price received when selling an item.',
      'pt-BR': 'Fração do preço base recebida ao vender um item.',
    },
  },
  {
    key: 'economy.isolation_mult',
    group: 'economy',
    type: 'json',
    min: 0,
    max: 10,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.economy.isolation_mult),
    description: {
      en: 'Price multiplier based on location isolation level.',
      'pt-BR': 'Multiplicador de preço baseado no nível de isolamento do local.',
    },
  },
  {
    key: 'economy.faction_mult',
    group: 'economy',
    type: 'json',
    min: 0,
    max: 10,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.economy.faction_mult),
    description: {
      en: 'Price multiplier based on faction standing.',
      'pt-BR': 'Multiplicador de preço baseado na reputação de facção.',
    },
  },
  {
    key: 'economy.mood_min',
    group: 'economy',
    type: 'number',
    min: 0,
    max: 2,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.economy.mood_min),
    description: {
      en: 'Lower bound of market mood fluctuation.',
      'pt-BR': 'Limite inferior da flutuação de humor do mercado.',
    },
  },
  {
    key: 'economy.mood_max',
    group: 'economy',
    type: 'number',
    min: 0,
    max: 2,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.economy.mood_max),
    description: {
      en: 'Upper bound of market mood fluctuation.',
      'pt-BR': 'Limite superior da flutuação de humor do mercado.',
    },
  },
  {
    key: 'economy.rarity_base_price',
    group: 'economy',
    type: 'json',
    min: 0,
    max: 50000,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.economy.rarity_base_price),
    description: {
      en: 'Base price per item rarity.',
      'pt-BR': 'Preço base por raridade de item.',
    },
  },
  {
    key: 'economy.payout_floor_integrity',
    group: 'economy',
    type: 'number',
    min: 0,
    max: 1,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.economy.payout_floor_integrity),
    description: {
      en: 'Minimum ship integrity required for full mission payout.',
      'pt-BR': 'Integridade mínima da nave necessária para pagamento integral da missão.',
    },
  },
  {
    key: 'economy.repair_seconds_per_point',
    group: 'economy',
    type: 'json',
    min: 0,
    max: 60,
    unit: 'seconds',
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.economy.repair_seconds_per_point),
    description: {
      en: 'Seconds required to repair one integrity point per location type.',
      'pt-BR': 'Segundos necessários para reparar um ponto de integridade por tipo de local.',
    },
  },
  {
    key: 'encounter.chance_divisor',
    group: 'encounter',
    type: 'integer',
    min: 1,
    max: 100,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.encounter.chance_divisor),
    description: {
      en: 'Divisor controlling random encounter probability.',
      'pt-BR': 'Divisor que controla a probabilidade de encontro aleatório.',
    },
  },
  {
    key: 'encounter.pirate_strength_options',
    group: 'encounter',
    type: 'json',
    min: 0.1,
    max: 5.0,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.encounter.pirate_strength_options),
    description: {
      en: 'Possible pirate strength multipliers.',
      'pt-BR': 'Multiplicadores de força pirata possíveis.',
    },
  },
  {
    key: 'encounter.pirate_mob_jitter',
    group: 'encounter',
    type: 'json',
    min: -5,
    max: 5,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.encounter.pirate_mob_jitter),
    description: {
      en: 'Possible mobility jitter values for pirate ships.',
      'pt-BR': 'Valores possíveis de variação de mobilidade para naves piratas.',
    },
  },
  {
    key: 'encounter.pirate_sen_jitter',
    group: 'encounter',
    type: 'json',
    min: -5,
    max: 5,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.encounter.pirate_sen_jitter),
    description: {
      en: 'Possible sensor jitter values for pirate ships.',
      'pt-BR': 'Valores possíveis de variação de sensores para naves piratas.',
    },
  },
  {
    key: 'encounter.pirate_bli_ratio',
    group: 'encounter',
    type: 'number',
    min: 0,
    max: 1,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.encounter.pirate_bli_ratio),
    description: {
      en: 'Baseline ratio of pirate build integrity.',
      'pt-BR': 'Razão base de integridade da construção pirata.',
    },
  },
  {
    key: 'encounter.pirate_min_pdf',
    group: 'encounter',
    type: 'integer',
    min: 0,
    max: 10,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.encounter.pirate_min_pdf),
    description: {
      en: 'Minimum pirate point defense fire.',
      'pt-BR': 'Fogo mínimo de defesa de ponto pirata.',
    },
  },
  {
    key: 'encounter.pirate_min_hp',
    group: 'encounter',
    type: 'integer',
    min: 1,
    max: 500,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.encounter.pirate_min_hp),
    description: {
      en: 'Minimum HP for a spawned pirate ship.',
      'pt-BR': 'HP mínimo para uma nave pirata gerada.',
    },
  },
  {
    key: 'escape.enemy_sen_weight',
    group: 'escape',
    type: 'integer',
    min: 0,
    max: 10,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.escape.enemy_sen_weight),
    description: {
      en: 'Enemy sensor contribution to escape difficulty.',
      'pt-BR': 'Contribuição dos sensores inimigos para dificuldade de fuga.',
    },
  },
  {
    key: 'escape.preset_bonus',
    group: 'escape',
    type: 'integer',
    min: 0,
    max: 10,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.escape.preset_bonus),
    description: {
      en: 'Bonus to escape rolls when engine preset is tuned for escape.',
      'pt-BR': 'Bônus em rolagens de fuga quando o preset do motor é ajustado para fuga.',
    },
  },
  {
    key: 'detection.ambush_per_sen_point',
    group: 'detection',
    type: 'number',
    min: 0,
    max: 1,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.detection.ambush_per_sen_point),
    description: {
      en: 'Ambush chance reduction per sensor point.',
      'pt-BR': 'Redução de chance de emboscada por ponto de sensor.',
    },
  },
  {
    key: 'detection.ambush_cap',
    group: 'detection',
    type: 'number',
    min: 0,
    max: 1,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.detection.ambush_cap),
    description: {
      en: 'Maximum ambush chance reduction from sensors.',
      'pt-BR': 'Redução máxima de chance de emboscada por sensores.',
    },
  },
  {
    key: 'stance.neutral_attack_ratio',
    group: 'stance',
    type: 'number',
    min: 0,
    max: 5,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.stance.neutral_attack_ratio),
    description: {
      en: 'Damage multiplier for attacks against neutral stance targets.',
      'pt-BR': 'Multiplicador de dano para ataques contra alvos de postura neutra.',
    },
  },
  {
    key: 'stance.rating_armor_weight',
    group: 'stance',
    type: 'integer',
    min: 0,
    max: 50,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.stance.rating_armor_weight),
    description: {
      en: 'Weight of armor in stance combat rating calculations.',
      'pt-BR': 'Peso da armadura nos cálculos de classificação de combate de postura.',
    },
  },
  {
    key: 'failure.tank_leak_min',
    group: 'failure',
    type: 'number',
    min: 0,
    max: 1,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.failure.tank_leak_min),
    description: {
      en: 'Minimum fuel loss ratio on a tank leak failure.',
      'pt-BR': 'Razão mínima de perda de combustível em falha de vazamento de tanque.',
    },
  },
  {
    key: 'failure.tank_leak_max',
    group: 'failure',
    type: 'number',
    min: 0,
    max: 1,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.failure.tank_leak_max),
    description: {
      en: 'Maximum fuel loss ratio on a tank leak failure.',
      'pt-BR': 'Razão máxima de perda de combustível em falha de vazamento de tanque.',
    },
  },
  {
    key: 'failure.weapon_skip_ratio',
    group: 'failure',
    type: 'number',
    min: 0,
    max: 1,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.failure.weapon_skip_ratio),
    description: {
      en: 'Chance that a worn weapon fails to fire.',
      'pt-BR': 'Chance de uma arma desgastada falhar ao disparar.',
    },
  },
  {
    key: 'integrity.combat_factor',
    group: 'integrity',
    type: 'number',
    min: 0,
    max: 1,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.integrity.combat_factor),
    description: {
      en: 'Integrity loss multiplier from combat damage.',
      'pt-BR': 'Multiplicador de perda de integridade por dano de combate.',
    },
  },
  {
    key: 'integrity.env_factor',
    group: 'integrity',
    type: 'number',
    min: 0,
    max: 1,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.integrity.env_factor),
    description: {
      en: 'Integrity loss multiplier from environmental hazards.',
      'pt-BR': 'Multiplicador de perda de integridade por perigos ambientais.',
    },
  },
  {
    key: 'mining.richness',
    group: 'mining',
    type: 'json',
    min: 0,
    max: 1,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.mining.richness),
    description: {
      en: 'Base ore richness per environment type.',
      'pt-BR': 'Riqueza base de minério por tipo de ambiente.',
    },
  },
  {
    key: 'mining.rarity',
    group: 'mining',
    type: 'json',
    min: 0,
    max: 1,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.mining.rarity),
    description: {
      en: 'Rarity threshold per material rarity.',
      'pt-BR': 'Limiar de raridade por raridade de material.',
    },
  },
  {
    key: 'mining.material_price',
    group: 'mining',
    type: 'json',
    min: 0,
    max: 10000,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.mining.material_price),
    description: {
      en: 'Base sell price per material rarity.',
      'pt-BR': 'Preço base de venda por raridade de material.',
    },
  },
  {
    key: 'mining.attempts_per_stop',
    group: 'mining',
    type: 'integer',
    min: 1,
    max: 100,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.mining.attempts_per_stop),
    description: {
      en: 'Number of mining attempts allowed per stop.',
      'pt-BR': 'Número de tentativas de mineração permitidas por parada.',
    },
  },
  {
    key: 'rescue.reference_mob',
    group: 'rescue',
    type: 'integer',
    min: 1,
    max: 10,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.rescue.reference_mob),
    description: {
      en: 'Reference mobility value used to compute rescue deadlines.',
      'pt-BR': 'Valor de mobilidade de referência usado para calcular prazos de resgate.',
    },
  },
  {
    key: 'rescue.deadline_factor_min',
    group: 'rescue',
    type: 'number',
    min: 1,
    max: 3,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.rescue.deadline_factor_min),
    description: {
      en: 'Minimum multiplier applied to rescue travel time for the deadline.',
      'pt-BR': 'Multiplicador mínimo aplicado ao tempo de viagem de resgate para o prazo.',
    },
  },
  {
    key: 'rescue.deadline_factor_max',
    group: 'rescue',
    type: 'number',
    min: 1,
    max: 5,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.rescue.deadline_factor_max),
    description: {
      en: 'Maximum multiplier applied to rescue travel time for the deadline.',
      'pt-BR': 'Multiplicador máximo aplicado ao tempo de viagem de resgate para o prazo.',
    },
  },
  {
    key: 'escort.encounter_multiplier',
    group: 'escort',
    type: 'number',
    min: 0,
    max: 5,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.escort.encounter_multiplier),
    description: {
      en: 'Encounter chance multiplier while escorting a client.',
      'pt-BR': 'Multiplicador de chance de encontro ao escoltar um cliente.',
    },
  },
  {
    key: 'escort.client_target_share',
    group: 'escort',
    type: 'number',
    min: 0,
    max: 1,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.escort.client_target_share),
    description: {
      en: 'Fraction of enemy fire directed at the escorted client.',
      'pt-BR': 'Fração do fogo inimigo direcionada ao cliente escoltado.',
    },
  },
  {
    key: 'ship_class.cargo_share',
    group: 'ship_class',
    type: 'number',
    min: 0,
    max: 1,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.ship_class.cargo_share),
    description: {
      en: 'Fraction of class budget allocated to cargo capacity.',
      'pt-BR': 'Fração do orçamento de classe alocada à capacidade de carga.',
    },
  },
  {
    key: 'ship_class.pressurized_share',
    group: 'ship_class',
    type: 'number',
    min: 0,
    max: 1,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.ship_class.pressurized_share),
    description: {
      en: 'Fraction of class budget allocated to pressurized sections.',
      'pt-BR': 'Fração do orçamento de classe alocada a seções pressurizadas.',
    },
  },
  {
    key: 'ship_class.combat_share',
    group: 'ship_class',
    type: 'number',
    min: 0,
    max: 1,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.ship_class.combat_share),
    description: {
      en: 'Fraction of class budget allocated to combat stats.',
      'pt-BR': 'Fração do orçamento de classe alocada a atributos de combate.',
    },
  },
  {
    key: 'missions.hold_max',
    group: 'missions',
    type: 'integer',
    min: 0,
    max: 10,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.missions.hold_max),
    description: {
      en: 'Maximum number of missions a player can place on hold.',
      'pt-BR': 'Número máximo de missões que um jogador pode deixar em espera.',
    },
  },
  {
    key: 'missions.active_max',
    group: 'missions',
    type: 'integer',
    min: 0,
    max: 10,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.missions.active_max),
    description: {
      en: 'Maximum number of active missions per player.',
      'pt-BR': 'Número máximo de missões ativas por jogador.',
    },
  },
  {
    key: 'missions.duration_k',
    group: 'missions',
    type: 'number',
    min: 0.1,
    max: 10,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.missions.duration_k),
    description: {
      en: 'Global multiplier for mission duration calculations.',
      'pt-BR': 'Multiplicador global para cálculos de duração de missão.',
    },
  },
  {
    key: 'missions.duration_class_cutoffs',
    group: 'missions',
    type: 'json',
    min: 60,
    max: 86400,
    unit: 'seconds',
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.missions.duration_class_cutoffs),
    description: {
      en: 'Duration thresholds used to classify mission lengths.',
      'pt-BR': 'Limiares de duração usados para classificar tamanhos de missão.',
    },
  },
  {
    key: 'missions.time_scale',
    group: 'missions',
    type: 'number',
    min: 0.001,
    max: 100,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.missions.time_scale),
    description: {
      en: 'Multiplier converting real seconds to in-universe mission time.',
      'pt-BR': 'Multiplicador que converte segundos reais em tempo de missão no universo.',
    },
  },
  {
    key: 'missions.board_min_per_location',
    group: 'missions',
    type: 'integer',
    min: 0,
    max: 20,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.missions.board_min_per_location),
    description: {
      en: 'Minimum number of missions posted per location on the board.',
      'pt-BR': 'Número mínimo de missões publicadas por local no quadro.',
    },
  },
  // DEFERRED (S8 review item 12): the `mission` chance (55%) is reserved. No SCAVENGING
  // MissionType exists in v0.1, so only `common` and `pirate` are read by scavenging.service.
  {
    key: 'scavenging.chance',
    group: 'scavenging',
    type: 'json',
    min: 0,
    max: 1,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.scavenging.chance),
    description: {
      en: 'Scavenging chance per source type.',
      'pt-BR': 'Chance de saque por tipo de fonte.',
    },
  },
  {
    key: 'scavenging.quality_min',
    group: 'scavenging',
    type: 'integer',
    min: 0,
    max: 100,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.scavenging.quality_min),
    description: {
      en: 'Minimum condition of scavenged parts.',
      'pt-BR': 'Condição mínima de peças saqueadas.',
    },
  },
  {
    key: 'scavenging.quality_max',
    group: 'scavenging',
    type: 'integer',
    min: 0,
    max: 100,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.scavenging.quality_max),
    description: {
      en: 'Maximum condition of scavenged parts.',
      'pt-BR': 'Condição máxima de peças saqueadas.',
    },
  },
  {
    key: 'scavenging.cooldown_seconds',
    group: 'scavenging',
    type: 'integer',
    min: 0,
    max: 86400,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.scavenging.cooldown_seconds),
    description: {
      en: 'Cooldown between scavenging attempts at the same location.',
      'pt-BR': 'Tempo de recarga entre tentativas de saque no mesmo local.',
    },
  },
  {
    key: 'parts.starter_condition',
    group: 'parts',
    type: 'integer',
    min: 0,
    max: 100,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.parts.starter_condition),
    description: {
      en: 'Condition of parts granted to a new ship.',
      'pt-BR': 'Condição das peças concedidas a uma nova nave.',
    },
  },
  {
    key: 'parts.restart_condition_max',
    group: 'parts',
    type: 'integer',
    min: 0,
    max: 100,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.parts.restart_condition_max),
    description: {
      en: 'Maximum condition of parts after a player restart.',
      'pt-BR': 'Condição máxima das peças após reinício do jogador.',
    },
  },
  {
    key: 'onboarding.starter_parts',
    group: 'onboarding',
    type: 'json',
    min: 0,
    max: 0,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.onboarding.starter_parts),
    description: {
      en: 'List of part types granted to a new player ship.',
      'pt-BR': 'Lista de tipos de peça concedidos à nave de um novo jogador.',
    },
  },
  {
    key: 'onboarding.home_locations',
    group: 'onboarding',
    type: 'json',
    min: 0,
    max: 0,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.onboarding.home_locations),
    description: {
      en: 'Starting home location per faction.',
      'pt-BR': 'Local inicial por facção.',
    },
  },
  {
    key: 'world.seed',
    group: 'world',
    type: 'string',
    min: 0,
    max: 0,
    factoryDefault: structuredClone(GAME_CONFIG_DEFAULTS.world.seed),
    description: {
      en: 'Deterministic seed for world generation and replay.',
      'pt-BR': 'Semente determinística para geração de mundo e replay.',
    },
  },
];

let registryByKey: Map<string, ConfigRegistryEntry> | undefined;

export function configRegistryByKey(): Map<string, ConfigRegistryEntry> {
  if (!registryByKey) {
    registryByKey = new Map(CONFIG_REGISTRY.map((entry) => [entry.key, entry]));
  }
  return registryByKey;
}

export function getRegistryEntry(key: string): ConfigRegistryEntry | undefined {
  return configRegistryByKey().get(key);
}

export function getConfigKeys(): readonly string[] {
  return CONFIG_REGISTRY.map((entry) => entry.key).sort();
}

export function getConfigGroups(): readonly string[] {
  return [...new Set(CONFIG_REGISTRY.map((entry) => entry.group))].sort();
}

export function isValidConfigKey(key: string): key is ConfigKey {
  return configRegistryByKey().has(key);
}

export function registerConfigRegistryEntry(entry: ConfigRegistryEntry): void {
  (CONFIG_REGISTRY as ConfigRegistryEntry[]).push(entry);
  registryByKey = undefined;
}
