-- E2: clearer part descriptions (what it does, why you need it, its trade-off).
-- The database owns this text (Admin edits win): a row is only rewritten while it still holds
-- the factory wording it was seeded with.
UPDATE "PartCatalog" SET "description" = $new${"en": "The command core of your ship. Every ship needs exactly one. It keeps the pilot alive if the rest of the ship is lost, and it sets how much structure (total build weight) the ship can carry.", "pt-BR": "O núcleo de comando da sua nave. Toda nave precisa de exatamente uma. Ela mantém o piloto vivo se o resto da nave for perdido e define quanta estrutura (peso total de construção) a nave aguenta."}$new$::jsonb
  WHERE "partType" = 'bridge' AND "description" = $old${"en": "Compact command module; provides structure budget rather than consuming it.", "pt-BR": "Módulo de comando compacto; fornece orçamento de estrutura em vez de consumi-lo."}$old$::jsonb;
UPDATE "PartCatalog" SET "description" = $new${"en": "A light rocket engine that moves the ship. It burns fuel, so you also need a fuel tank. Cheap and thrifty, but too weak to push a heavy ship fast.", "pt-BR": "Um motor a foguete leve que move a nave. Ele queima combustível, então você também precisa de um tanque. Barato e econômico, mas fraco demais para mover uma nave pesada rápido."}$new$::jsonb
  WHERE "partType" = 'engine_chem_small' AND "description" = $old${"en": "Light chemical thruster for small hulls.", "pt-BR": "Propulsor químico leve para cascos pequenos."}$old$::jsonb;
UPDATE "PartCatalog" SET "description" = $new${"en": "The all-round engine: clearly more thrust than the small one, for more fuel use and mass. A good fit for ships that carry cargo or armor. Needs a fuel tank.", "pt-BR": "O motor versátil: bem mais empuxo que o pequeno, com mais consumo e massa. Serve bem para naves com carga ou blindagem. Precisa de um tanque de combustível."}$new$::jsonb
  WHERE "partType" = 'engine_chem_medium' AND "description" = $old${"en": "Balanced chemical engine for medium ships.", "pt-BR": "Motor químico equilibrado para naves médias."}$old$::jsonb;
UPDATE "PartCatalog" SET "description" = $new${"en": "Big thrust for big ships. Moves heavy cargo or warship builds at a decent speed, but it is heavy, takes a 2×2 block and burns fuel fast. Needs a fuel tank.", "pt-BR": "Muito empuxo para naves grandes. Move construções pesadas de carga ou guerra numa velocidade decente, mas é pesado, ocupa um bloco 2×2 e queima combustível rápido. Precisa de um tanque de combustível."}$new$::jsonb
  WHERE "partType" = 'engine_chem_large' AND "description" = $old${"en": "Heavy chemical engine for large cargo or combat hulls.", "pt-BR": "Motor químico pesado para cascos grandes de carga ou combate."}$old$::jsonb;
UPDATE "PartCatalog" SET "description" = $new${"en": "A tiny electric drive that burns no fuel, so no tank is needed. Its thrust is low: good for light ships and long trips where refuelling is a hassle. Needs steady power from a reactor or solar panel.", "pt-BR": "Um pequeno motor elétrico que não queima combustível, então não precisa de tanque. O empuxo é baixo: bom para naves leves e viagens longas em que reabastecer é um problema. Precisa de energia constante de um reator ou painel solar."}$new$::jsonb
  WHERE "partType" = 'engine_ion_micro' AND "description" = $old${"en": "Tiny ionic drive with no fuel use; tournament-tested motor_pp.", "pt-BR": "Propulsor iônico minúsculo sem consumo de combustível; motor_pp validado no torneio."}$old$::jsonb;
UPDATE "PartCatalog" SET "description" = $new${"en": "Holds your fuel. Every chemical engine burns fuel, so a ship with one needs at least one tank; more tanks mean more range between refuels. Adds mass and uses structure.", "pt-BR": "Guarda o seu combustível. Todo motor químico queima combustível, então uma nave com um precisa de pelo menos um tanque; mais tanques significam mais alcance entre reabastecimentos. Adiciona massa e usa estrutura."}$new$::jsonb
  WHERE "partType" = 'tank_small' AND "description" = $old${"en": "Small tank holding 1000 fuel units.", "pt-BR": "Tanque pequeno com capacidade para 1000 unidades de combustível."}$old$::jsonb;
UPDATE "PartCatalog" SET "description" = $new${"en": "Stores energy for combat. Shields and lasers draw from it during a fight, and if it cannot cover their demand the ship is not allowed to fly. Small and cheap.", "pt-BR": "Guarda energia para o combate. Escudos e lasers consomem dela durante a luta, e se ela não cobre a demanda a nave não pode voar. Pequena e barata."}$new$::jsonb
  WHERE "partType" = 'battery_small' AND "description" = $old${"en": "Compact power cell for small ships.", "pt-BR": "Célula de energia compacta para naves pequenas."}$old$::jsonb;
UPDATE "PartCatalog" SET "description" = $new${"en": "A large energy store for power-hungry builds (lasers plus a shield). Far more charge and output than the small battery, but heavy and a 1×2 block.", "pt-BR": "Um grande estoque de energia para construções famintas por energia (lasers mais escudo). Muito mais carga e saída que a bateria pequena, mas pesada e ocupa um bloco 1×2."}$new$::jsonb
  WHERE "partType" = 'battery_large' AND "description" = $old${"en": "High-capacity battery bank for energy-hungry builds.", "pt-BR": "Banco de baterias de alta capacidade para construções energéticas."}$old$::jsonb;
UPDATE "PartCatalog" SET "description" = $new${"en": "A basic cannon. Cheap, reliable damage that needs no energy: a good first weapon for escort missions. Modest firepower.", "pt-BR": "Um canhão básico. Dano barato e confiável que não usa energia: uma boa primeira arma para missões de escolta. Poder de fogo modesto."}$new$::jsonb
  WHERE "partType" = 'weapon_ballistic' AND "description" = $old${"en": "Reliable ballistic cannon for close-range fire.", "pt-BR": "Canhão balístico confiável para fogo de curto alcance."}$old$::jsonb;
UPDATE "PartCatalog" SET "description" = $new${"en": "A precise energy weapon with more firepower than the cannon. It draws combat energy from your batteries every round, so pair it with a battery.", "pt-BR": "Uma arma de energia precisa, com mais poder de fogo que o canhão. Consome energia de combate das baterias a cada rodada, então use com uma bateria."}$new$::jsonb
  WHERE "partType" = 'weapon_laser' AND "description" = $old${"en": "Precision energy weapon that drains capacitors in combat.", "pt-BR": "Arma de energia de precisão que drena capacitores em combate."}$old$::jsonb;
UPDATE "PartCatalog" SET "description" = $new${"en": "Heavy missiles: the highest firepower of any weapon, paid for in size (1×2), mass and price. Rare. Take it when you expect to fight.", "pt-BR": "Mísseis pesados: o maior poder de fogo entre as armas, pago em tamanho (1×2), massa e preço. Rara. Leve quando espera lutar."}$new$::jsonb
  WHERE "partType" = 'weapon_missile' AND "description" = $old${"en": "Slow-firing missile launcher with high burst damage.", "pt-BR": "Lançador de mísseis de disparo lento com alto dano em rajada."}$old$::jsonb;
UPDATE "PartCatalog" SET "description" = $new${"en": "Heavy armor plating: the most protection per part, cutting the damage from every hit. Very heavy, so it slows your ship down.", "pt-BR": "Placa de blindagem pesada: a maior proteção por peça, reduzindo o dano de cada ataque. Muito pesada, então deixa a nave mais lenta."}$new$::jsonb
  WHERE "partType" = 'armor_plate' AND "description" = $old${"en": "Heavy plating that absorbs kinetic impacts.", "pt-BR": "Blindagem pesada que absorve impactos cinéticos."}$old$::jsonb;
UPDATE "PartCatalog" SET "description" = $new${"en": "A cheap, light structural frame with a little armor. Adds hit points and a touch of protection, but no speed, cargo or firepower.", "pt-BR": "Uma estrutura barata e leve com um pouco de blindagem. Adiciona pontos de casco e um toque de proteção, mas nenhuma velocidade, carga ou poder de fogo."}$new$::jsonb
  WHERE "partType" = 'hull' AND "description" = $old${"en": "Basic structural frame with light armor.", "pt-BR": "Estrutura básica com armadura leve."}$old$::jsonb;
UPDATE "PartCatalog" SET "description" = $new${"en": "An energy shield: absorbs damage first and recharges between rounds of a fight. Draws combat energy, so it needs a battery. Great against pirates; useless if the battery cannot power it.", "pt-BR": "Um escudo de energia: absorve o dano primeiro e recarrega entre as rodadas da luta. Consome energia de combate, então precisa de bateria. Ótimo contra piratas; inútil se a bateria não conseguir alimentá-lo."}$new$::jsonb
  WHERE "partType" = 'shield_basic' AND "description" = $old${"en": "Energy shield that regenerates between combat exchanges.", "pt-BR": "Escudo de energia que se regenera entre trocas de combate."}$old$::jsonb;
UPDATE "PartCatalog" SET "description" = $new${"en": "Long-range sensors that spot ambushes before they happen, lowering the chance of being caught by pirates. Draws a little power all the time.", "pt-BR": "Sensores de longo alcance que detectam emboscadas antes que aconteçam, reduzindo a chance de ser pego por piratas. Consome um pouco de energia o tempo todo."}$new$::jsonb
  WHERE "partType" = 'sensor_radar' AND "description" = $old${"en": "Long-range sensor array for navigation and ambush avoidance.", "pt-BR": "Array de sensores de longo alcance para navegação e evasão de emboscadas."}$old$::jsonb;
UPDATE "PartCatalog" SET "description" = $new${"en": "Cargo space. Each hold adds capacity for deliveries, so more holds mean bigger, better-paid jobs. Adds mass, which slows the ship.", "pt-BR": "Espaço de carga. Cada compartimento aumenta a capacidade para entregas, então mais compartimentos significam trabalhos maiores e mais bem pagos. Adiciona massa, o que deixa a nave mais lenta."}$new$::jsonb
  WHERE "partType" = 'cargo' AND "description" = $old${"en": "Pressurized cargo module for freight missions.", "pt-BR": "Módulo de carga pressurizado para missões de frete."}$old$::jsonb;
UPDATE "PartCatalog" SET "description" = $new${"en": "An automated extractor. Needed for mining missions and for pulling ore out of asteroid fields, which you sell at ports. Draws steady power and adds mass.", "pt-BR": "Um extrator automático. Necessária para missões de mineração e para tirar minério de campos de asteroides, que você vende nos portos. Consome energia constante e adiciona massa."}$new$::jsonb
  WHERE "partType" = 'mining_rig' AND "description" = $old${"en": "Automated extractor for asteroid and debris mining.", "pt-BR": "Extrator automatizado para mineração de asteroides e detritos."}$old$::jsonb;
UPDATE "PartCatalog" SET "description" = $new${"en": "A light solar array with a small but constant power output. Covers what engines, radar and rigs draw in flight at almost no weight.", "pt-BR": "Um painel solar leve com produção de energia pequena, mas constante. Cobre o que motores, radar e mineradoras consomem em voo, com quase nenhum peso."}$new$::jsonb
  WHERE "partType" = 'reactor_solar' AND "description" = $old${"en": "Light photovoltaic array for continuous low output.", "pt-BR": "Array fotovoltaico leve para saída contínua baixa."}$old$::jsonb;
UPDATE "PartCatalog" SET "description" = $new${"en": "A heavy fission reactor with a very large power output, for builds full of power-hungry parts. Rare, expensive and heavy (2×2).", "pt-BR": "Um reator de fissão pesado com produção de energia muito alta, para construções cheias de peças que consomem muita energia. Raro, caro e pesado (2×2)."}$new$::jsonb
  WHERE "partType" = 'reactor_nuclear' AND "description" = $old${"en": "Heavy fission reactor for high energy budgets.", "pt-BR": "Reator de fissão pesado para orçamentos energéticos altos."}$old$::jsonb;
